use GD2C2022
go

--DROPS FK

IF OBJECT_ID('CODIGO_ENIGMA.FK_C_MEDIO_PAGO_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.COMPRA DROP CONSTRAINT FK_C_MEDIO_PAGO_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_PROVEEDOR_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.COMPRA DROP CONSTRAINT FK_PROVEEDOR_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_DESCUENTO_COMPRA_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.COMPRA DROP CONSTRAINT FK_DESCUENTO_COMPRA_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_PROVEEDOR_LOCALIDAD_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.PROVEEDOR DROP CONSTRAINT FK_PROVEEDOR_LOCALIDAD_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_PROVINCIA_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.LOCALIDAD DROP CONSTRAINT FK_PROVINCIA_CODIGO  
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_COMPRA_NUMERO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.COMPRAxPRODUCTO DROP CONSTRAINT FK_COMPRA_NUMERO 
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_CP_PRODUCTO_VARIANTE_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.COMPRAxPRODUCTO DROP CONSTRAINT FK_CP_PRODUCTO_VARIANTE_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_TIPO_VARIANTE_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.PRODUCTO_VARIANTE DROP CONSTRAINT FK_TIPO_VARIANTE_CODIGO   
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_PRODUCTO_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.PRODUCTO_VARIANTE DROP CONSTRAINT FK_PRODUCTO_CODIGO   
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_PRODUCTO_CATEGORIA_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.PRODUCTO DROP CONSTRAINT FK_PRODUCTO_CATEGORIA_CODIGO  
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_CLIENTE_LOCALIDAD_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.CLIENTE DROP CONSTRAINT FK_CLIENTE_LOCALIDAD_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_VP_PRODUCTO_VARIANTE_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.VENTAxPRODUCTO DROP CONSTRAINT FK_VP_PRODUCTO_VARIANTE_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_VENTA_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.VENTAxPRODUCTO DROP CONSTRAINT FK_VENTA_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_CLIENTE_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.VENTA DROP CONSTRAINT FK_CLIENTE_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_MEDIO_PAGO_VENTA_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.VENTA DROP CONSTRAINT FK_MEDIO_PAGO_VENTA_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_CANAL_VENTA_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.VENTA DROP CONSTRAINT FK_CANAL_VENTA_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_MEDIO_ENVIO_VENTA_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.VENTA DROP CONSTRAINT FK_MEDIO_ENVIO_VENTA_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_VENTA_CUPON_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.CUPONxVENTA DROP CONSTRAINT FK_VENTA_CUPON_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_CV_VENTA_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.CUPONxVENTA DROP CONSTRAINT FK_CV_VENTA_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_MEDIO_ENVIO_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.MEDIO_ENVIO_VENTA DROP CONSTRAINT FK_MEDIO_ENVIO_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_LOCALIDAD_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.MEDIO_ENVIO_VENTA DROP CONSTRAINT FK_LOCALIDAD_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_DES_VENTA_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.DESCUENTO_VENTA DROP CONSTRAINT FK_DES_VENTA_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_TIPO_DESCUENTO_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.DESCUENTO_VENTA DROP CONSTRAINT FK_TIPO_DESCUENTO_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_CANAL_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.CANAL_VENTA DROP CONSTRAINT FK_CANAL_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.FK_MPV_MEDIO_PAGO_CODIGO', 'F') IS NOT NULL
  ALTER TABLE CODIGO_ENIGMA.MEDIO_PAGO_VENTA DROP CONSTRAINT FK_MPV_MEDIO_PAGO_CODIGO
GO


--DROPS TABLAS

IF OBJECT_ID('CODIGO_ENIGMA.PROVEEDOR', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.PROVEEDOR
GO

IF OBJECT_ID('CODIGO_ENIGMA.COMPRA', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.COMPRA
GO

IF OBJECT_ID('CODIGO_ENIGMA.DESCUENTO_COMPRA', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.DESCUENTO_COMPRA
GO

IF OBJECT_ID('CODIGO_ENIGMA.COMPRAxPRODUCTO', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.COMPRAxPRODUCTO
GO

IF OBJECT_ID('CODIGO_ENIGMA.PRODUCTO', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.PRODUCTO
GO

IF OBJECT_ID('CODIGO_ENIGMA.PRODUCTO_CATEGORIA', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.PRODUCTO_CATEGORIA
GO

IF OBJECT_ID('CODIGO_ENIGMA.PRODUCTO_VARIANTE', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.PRODUCTO_VARIANTE
GO

IF OBJECT_ID('CODIGO_ENIGMA.TIPO_VARIANTE', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.TIPO_VARIANTE
GO

IF OBJECT_ID('CODIGO_ENIGMA.PROVINCIA', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.PROVINCIA
GO

IF OBJECT_ID('CODIGO_ENIGMA.LOCALIDAD', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.LOCALIDAD
GO

IF OBJECT_ID('CODIGO_ENIGMA.MEDIO_PAGO', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.MEDIO_PAGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.CLIENTE', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.CLIENTE
GO

IF OBJECT_ID('CODIGO_ENIGMA.VENTAxPRODUCTO', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.VENTAxPRODUCTO
GO

IF OBJECT_ID('CODIGO_ENIGMA.VENTA', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.VENTA
GO

IF OBJECT_ID('CODIGO_ENIGMA.CUPONxVENTA', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.CUPONxVENTA
GO

IF OBJECT_ID('CODIGO_ENIGMA.VENTA_CUPON', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.VENTA_CUPON
GO

IF OBJECT_ID('CODIGO_ENIGMA.MEDIO_ENVIO_VENTA', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.MEDIO_ENVIO_VENTA
GO

IF OBJECT_ID('CODIGO_ENIGMA.MEDIO_ENVIO', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.MEDIO_ENVIO
GO

IF OBJECT_ID('CODIGO_ENIGMA.DESCUENTO_VENTA', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.DESCUENTO_VENTA
GO

IF OBJECT_ID('CODIGO_ENIGMA.TIPO_DESCUENTO', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.TIPO_DESCUENTO
GO

IF OBJECT_ID('CODIGO_ENIGMA.CANAL_VENTA', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.CANAL_VENTA
GO

IF OBJECT_ID('CODIGO_ENIGMA.CANAL', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.CANAL
GO

IF OBJECT_ID('CODIGO_ENIGMA.MEDIO_PAGO_VENTA', 'U') IS NOT NULL
  DROP TABLE CODIGO_ENIGMA.MEDIO_PAGO_VENTA
GO


--DROPS FUNCIONES

IF OBJECT_ID('CODIGO_ENIGMA.OBTENER_PROVINCIA_CODIGO') IS NOT NULL
	DROP FUNCTION CODIGO_ENIGMA.OBTENER_PROVINCIA_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.OBTENER_LOCALIDAD_CODIGO') IS NOT NULL
	DROP FUNCTION CODIGO_ENIGMA.OBTENER_LOCALIDAD_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.OBTENER_PROVEEDOR_CODIGO') IS NOT NULL
	DROP FUNCTION CODIGO_ENIGMA.OBTENER_PROVEEDOR_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.OBTENER_MEDIO_PAGO_CODIGO') IS NOT NULL
	DROP FUNCTION CODIGO_ENIGMA.OBTENER_MEDIO_PAGO_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.OBTENER_TIPO_VARIANTE_CODIGO') IS NOT NULL
	DROP FUNCTION CODIGO_ENIGMA.OBTENER_TIPO_VARIANTE_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.OBTENER_PRODUCTO_CATEGORIA_CODIGO') IS NOT NULL
	DROP FUNCTION CODIGO_ENIGMA.OBTENER_PRODUCTO_CATEGORIA_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.OBTENER_DESCUENTO_COMPRA_CODIGO') IS NOT NULL
	DROP FUNCTION CODIGO_ENIGMA.OBTENER_DESCUENTO_COMPRA_CODIGO
GO


IF OBJECT_ID('CODIGO_ENIGMA.OBTENER_TIPO_DESCUENTO_CODIGO') IS NOT NULL
	DROP FUNCTION CODIGO_ENIGMA.OBTENER_TIPO_DESCUENTO_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.OBTENER_MEDIO_ENVIO_CODIGO') IS NOT NULL
	DROP FUNCTION CODIGO_ENIGMA.OBTENER_MEDIO_ENVIO_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.OBTENER_CANAL_CODIGO') IS NOT NULL
	DROP FUNCTION CODIGO_ENIGMA.OBTENER_CANAL_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.OBTENER_CLIENTE_CODIGO') IS NOT NULL
	DROP FUNCTION CODIGO_ENIGMA.OBTENER_CLIENTE_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.OBTENER_MEDIO_ENVIO_VENTA_CODIGO') IS NOT NULL
	DROP FUNCTION CODIGO_ENIGMA.OBTENER_MEDIO_ENVIO_VENTA_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.OBTENER_MEDIO_PAGO_VENTA_CODIGO') IS NOT NULL
	DROP FUNCTION CODIGO_ENIGMA.OBTENER_MEDIO_PAGO_VENTA_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.OBTENER_CANAL_VENTA_CODIGO') IS NOT NULL
	DROP FUNCTION CODIGO_ENIGMA.OBTENER_CANAL_VENTA_CODIGO
GO

IF OBJECT_ID('CODIGO_ENIGMA.OBTENER_PRODUCTO_VARIANTE_CODIGO') IS NOT NULL
	DROP FUNCTION CODIGO_ENIGMA.OBTENER_PRODUCTO_VARIANTE_CODIGO
GO

--DROPS PROCEDURES

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_PROVINCIA') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_PROVINCIA
GO 

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_LOCALIDAD') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_LOCALIDAD
GO  

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_PROVEEDOR') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_PROVEEDOR
GO 

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_DESCUENTO_COMPRA') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_DESCUENTO_COMPRA
GO 

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_MEDIO_PAGO') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_MEDIO_PAGO
GO 

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_TIPO_VARIANTE') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_TIPO_VARIANTE
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_PRODUCTO_CATEGORIA') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_PRODUCTO_CATEGORIA
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_PRODUCTO') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_PRODUCTO
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_PRODUCTO_VARIANTE') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_PRODUCTO_VARIANTE
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_COMPRA') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_COMPRA
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_COMPRAxPRODUCTO') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_COMPRAxPRODUCTO
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_CLIENTE') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_CLIENTE
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_VENTAxPRODUCTO') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_VENTAxPRODUCTO
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_VENTA') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_VENTA
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_CUPONxVENTA') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_CUPONxVENTA
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_VENTA_CUPON') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_VENTA_CUPON
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_MEDIO_ENVIO_VENTA') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_MEDIO_ENVIO_VENTA
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_MEDIO_ENVIO') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_MEDIO_ENVIO
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_DESCUENTO_VENTA') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_DESCUENTO_VENTA
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_TIPO_DESCUENTO') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_TIPO_DESCUENTO
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_CANAL_VENTA') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_CANAL_VENTA
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_CANAL') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_CANAL
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_MEDIO_PAGO_VENTA') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_MEDIO_PAGO_VENTA
GO

IF OBJECT_ID('CODIGO_ENIGMA.migrar_medio_envio') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.migrar_medio_envio
GO

IF OBJECT_ID('CODIGO_ENIGMA.migrar_medio_envio_venta') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.migrar_medio_envio_venta
GO

IF OBJECT_ID('CODIGO_ENIGMA.migrar_medio_pago_venta') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.migrar_medio_pago_venta
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_CANAL_VENTA') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_CANAL_VENTA
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_VENTA') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_VENTA
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_TIPO_DESCUENTO') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_TIPO_DESCUENTO
GO

IF OBJECT_ID('CODIGO_ENIGMA.MIGRAR_DESCUENTO_VENTA') IS NOT NULL
  DROP PROCEDURE CODIGO_ENIGMA.MIGRAR_DESCUENTO_VENTA
GO
--DROP SCHEMA

IF EXISTS (SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'CODIGO_ENIGMA')
  DROP SCHEMA CODIGO_ENIGMA
GO


--CREACION SCHEMA

CREATE SCHEMA CODIGO_ENIGMA
GO


--CREACION TABLAS

CREATE TABLE CODIGO_ENIGMA.LOCALIDAD (
   	LOCALIDAD_CODIGO INT IDENTITY(1,1) NOT NULL,
	LOCALIDAD_NOMBRE NVARCHAR(255) ,
	LOCALIDAD_CODIGO_POSTAL DECIMAL(18,0) ,
	PROVINCIA_CODIGO INT
);
GO

CREATE TABLE CODIGO_ENIGMA.PROVINCIA (
	PROVINCIA_CODIGO INT IDENTITY(1,1) NOT NULL,
	PROVINCIA_NOMBRE NVARCHAR(255)
);
GO

CREATE TABLE CODIGO_ENIGMA.PROVEEDOR (
   	PROVEEDOR_CODIGO INT IDENTITY(1,1) NOT NULL,
   	PROVEEDOR_RAZON_SOCIAL NVARCHAR(50) ,
   	PROVEEDOR_CUIT  NVARCHAR(50) ,
   	PROVEEDOR_DOMICILIO  NVARCHAR(50) ,
   	PROVEEDOR_MAIL  NVARCHAR(50) ,
	LOCALIDAD_CODIGO INT
);
GO

CREATE TABLE CODIGO_ENIGMA.DESCUENTO_COMPRA (
	DESCUENTO_COMPRA_CODIGO DECIMAL (19,0) NOT NULL,
   	DESCUENTO_COMPRA_VALOR DECIMAL(18,2)
);
GO

CREATE TABLE CODIGO_ENIGMA.COMPRA (
   	COMPRA_NUMERO DECIMAL (19,0) NOT NULL,
   	COMPRA_FECHA DATETIME,
   	COMPRA_TOTAL  DECIMAL(18,2),
	MEDIO_PAGO_CODIGO INT,
   	PROVEEDOR_CODIGO  INT,
	DESCUENTO_COMPRA_CODIGO DECIMAL(19,0) 
);
GO

CREATE TABLE CODIGO_ENIGMA.COMPRAxPRODUCTO (
	COMPRA_X_PRODUCTO_CODIGO INT IDENTITY(1,1) NOT NULL,
   	COMPRA_NUMERO DECIMAL (19,0),
   	PRODUCTO_VARIANTE_CODIGO INT,
   	COMPRA_PRODUCTO_CANTIDAD  decimal(18,0)
);
GO

CREATE TABLE CODIGO_ENIGMA.PRODUCTO (
   	PRODUCTO_CODIGO NVARCHAR(50) NOT NULL,
   	PRODUCTO_NOMBRE NVARCHAR(50),
	PRODUCTO_DESCRIPCION NVARCHAR(50),
   	PRODUCTO_MARCA NVARCHAR(255),
	PRODUCTO_MATERIAL NVARCHAR(50),
	PRODUCTO_CATEGORIA_CODIGO INT
);
GO

CREATE TABLE CODIGO_ENIGMA.PRODUCTO_CATEGORIA (
   	PRODUCTO_CATEGORIA_CODIGO INT IDENTITY(1,1) NOT NULL,
   	PRODUCTO_CATEGORIA NVARCHAR(255)
);
GO

CREATE TABLE CODIGO_ENIGMA.PRODUCTO_VARIANTE (
   	PRODUCTO_VARIANTE_CODIGO INT IDENTITY(1,1) NOT NULL,
	PRODUCTO_VARIANTE_ID NVARCHAR(50),
   	PRODUCTO_VARIANTE NVARCHAR(50),
	TIPO_VARIANTE_CODIGO INT,
	PRODUCTO_CODIGO NVARCHAR(50),
	PRODUCTO_VARIANTE_PRECIO decimal(18,2)
);
GO

CREATE TABLE CODIGO_ENIGMA.TIPO_VARIANTE (
   	TIPO_VARIANTE_CODIGO INT IDENTITY(1,1) NOT NULL,
	PRODUCTO_TIPO_VARIANTE NVARCHAR(50)
);
GO

CREATE TABLE CODIGO_ENIGMA.MEDIO_PAGO (
	MEDIO_PAGO_CODIGO INT IDENTITY(1,1) NOT NULL,
	MEDIO_PAGO NVARCHAR(255)
);
GO

CREATE TABLE CODIGO_ENIGMA.CLIENTE (
   	CLIENTE_CODIGO INT IDENTITY(1,1) NOT NULL,
   	CLIENTE_NOMBRE NVARCHAR(255),
	CLIENTE_APELLIDO NVARCHAR(255),
	CLIENTE_DNI decimal(18,0),
	CLIENTE_DIRECCION NVARCHAR(255),
	CLIENTE_TELEFONO decimal(18,0),
	CLIENTE_MAIL NVARCHAR(255),
	CLIENTE_FECHA_NAC DATETIME,
	LOCALIDAD_CODIGO INT 
);
GO

CREATE TABLE CODIGO_ENIGMA.VENTAxPRODUCTO (
	VENTA_X_PRODUCTO_CODIGO INT IDENTITY(1,1) NOT NULL,
	VENTA_CODIGO DECIMAL(19,0) NOT NULL,
	PRODUCTO_VARIANTE_CODIGO INT NOT NULL,
	VENTA_PRODUCTO_CANTIDAD DECIMAL(18,0)
);
GO

CREATE TABLE CODIGO_ENIGMA.VENTA (
	VENTA_CODIGO DECIMAL(19,0) NOT NULL, 
	VENTA_FECHA DATETIME,
	VENTA_TOTAL DECIMAL(18,2),
	CLIENTE_CODIGO INT,
	MEDIO_PAGO_VENTA_CODIGO INT,
	CANAL_VENTA_CODIGO INT,
	MEDIO_ENVIO_VENTA_CODIGO INT
);
GO

CREATE TABLE CODIGO_ENIGMA.CUPONxVENTA (
	VENTAxCUPON_CODIGO INT IDENTITY(1,1) NOT NULL,
	VENTA_CUPON_CODIGO NVARCHAR(50) NOT NULL, 
	VENTA_CODIGO DECIMAL(19,0) NOT NULL,
	VENTA_CUPON_IMPORTE DECIMAL(18,2)
);
GO

CREATE TABLE CODIGO_ENIGMA.VENTA_CUPON (
	VENTA_CUPON_CODIGO NVARCHAR(50) NOT NULL,
	VENTA_CUPON_FECHA_DESDE DATETIME,
	VENTA_CUPON_FECHA_HASTA DATETIME,
	VENTA_CUPON_VALOR DECIMAL(18,0),
	VENTA_CUPON_TIPO NVARCHAR(50)
);
GO

CREATE TABLE CODIGO_ENIGMA.MEDIO_ENVIO_VENTA (
	MEDIO_ENVIO_VENTA_CODIGO INT IDENTITY(1,1) NOT NULL,
	VENTA_ENVIO_PRECIO DECIMAL(18,2),
	VENTA_ENVIO_TIEMPO DECIMAL(18,2),
	MEDIO_ENVIO_CODIGO INT,
	LOCALIDAD_CODIGO INT
);
GO

CREATE TABLE CODIGO_ENIGMA.MEDIO_ENVIO (
	MEDIO_ENVIO_CODIGO INT IDENTITY(1,1) NOT NULL,
	VENTA_MEDIO_ENVIO NVARCHAR(255)
);
GO

CREATE TABLE CODIGO_ENIGMA.DESCUENTO_VENTA (
	VENTA_DESCUENTO_CODIGO INT IDENTITY(1,1) NOT NULL,
	VENTA_DESCUENTO_IMPORTE DECIMAL(18,2),
	VENTA_CODIGO DECIMAL(19,0),
	TIPO_DESCUENTO_CODIGO INT
);
GO

CREATE TABLE CODIGO_ENIGMA.TIPO_DESCUENTO (
	TIPO_DESCUENTO_CODIGO INT IDENTITY(1,1) NOT NULL,
	VENTA_DESCUENTO_CONCEPTO NVARCHAR(255)
);
GO

CREATE TABLE CODIGO_ENIGMA.CANAL_VENTA (
	CANAL_VENTA_CODIGO INT IDENTITY(1,1) NOT NULL,
	VENTA_CANAL_COSTO DECIMAL(18,2),
	CANAL_CODIGO INT
);
GO

CREATE TABLE CODIGO_ENIGMA.CANAL (
	CANAL_CODIGO INT IDENTITY(1,1) NOT NULL,
	VENTA_CANAL NVARCHAR(255)
);
GO

CREATE TABLE CODIGO_ENIGMA.MEDIO_PAGO_VENTA (
	MEDIO_PAGO_VENTA_CODIGO INT IDENTITY(1,1) NOT NULL,
	VENTA_MEDIO_PAGO_COSTO DECIMAL(18,2),
	MEDIO_PAGO_CODIGO INT
);
GO

--PRIMARY KEYS

ALTER TABLE CODIGO_ENIGMA.PROVEEDOR ADD CONSTRAINT PK_PROVEEDOR PRIMARY KEY(PROVEEDOR_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.COMPRA ADD CONSTRAINT PK_COMPRA_NUMERO PRIMARY KEY(COMPRA_NUMERO)
GO

ALTER TABLE CODIGO_ENIGMA.DESCUENTO_COMPRA ADD CONSTRAINT PK_DESCUENTO_COMPRA PRIMARY KEY(DESCUENTO_COMPRA_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.COMPRAxPRODUCTO ADD CONSTRAINT PK_COMPRAxPRODUCTO PRIMARY KEY(COMPRA_X_PRODUCTO_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.PRODUCTO ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY(PRODUCTO_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.PRODUCTO_CATEGORIA ADD CONSTRAINT PK_PRODUCTO_CATEGORIA PRIMARY KEY(PRODUCTO_CATEGORIA_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.PRODUCTO_VARIANTE ADD CONSTRAINT PK_PRODUCTO_VARIANTE PRIMARY KEY(PRODUCTO_VARIANTE_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.TIPO_VARIANTE ADD CONSTRAINT PK_TIPO_VARIANTE PRIMARY KEY(TIPO_VARIANTE_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.LOCALIDAD ADD CONSTRAINT PK_LOCALIDAD PRIMARY KEY(LOCALIDAD_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.PROVINCIA ADD CONSTRAINT PK_PROVINCIA PRIMARY KEY(PROVINCIA_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.MEDIO_PAGO ADD CONSTRAINT PK_MEDIO_PAGO PRIMARY KEY(MEDIO_PAGO_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY(CLIENTE_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.VENTAxPRODUCTO ADD CONSTRAINT PK_VENTAxPRODUCTO PRIMARY KEY(VENTA_X_PRODUCTO_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.VENTA ADD CONSTRAINT PK_VENTA PRIMARY KEY(VENTA_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.CUPONxVENTA ADD CONSTRAINT PK_CUPONxVENTA PRIMARY KEY(VENTAxCUPON_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.VENTA_CUPON ADD CONSTRAINT PK_VENTA_CUPON PRIMARY KEY(VENTA_CUPON_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.MEDIO_ENVIO_VENTA ADD CONSTRAINT PK_MEDIO_ENVIO_VENTA PRIMARY KEY(MEDIO_ENVIO_VENTA_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.MEDIO_ENVIO ADD CONSTRAINT PK_MEDIO_ENVIO PRIMARY KEY(MEDIO_ENVIO_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.DESCUENTO_VENTA ADD CONSTRAINT PK_DESCUENTO_VENTA PRIMARY KEY(VENTA_DESCUENTO_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.TIPO_DESCUENTO ADD CONSTRAINT PK_TIPO_DESCUENTO PRIMARY KEY(TIPO_DESCUENTO_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.CANAL_VENTA ADD CONSTRAINT PK_CANAL_VENTA PRIMARY KEY(CANAL_VENTA_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.CANAL ADD CONSTRAINT PK_CANAL PRIMARY KEY(CANAL_CODIGO)
GO

ALTER TABLE CODIGO_ENIGMA.MEDIO_PAGO_VENTA ADD CONSTRAINT PK_MEDIO_PAGO_VENTA PRIMARY KEY(MEDIO_PAGO_VENTA_CODIGO)
GO


--FOREGIN KEYS
ALTER TABLE CODIGO_ENIGMA.LOCALIDAD ADD CONSTRAINT FK_PROVINCIA_CODIGO FOREIGN KEY(PROVINCIA_CODIGO) REFERENCES CODIGO_ENIGMA.PROVINCIA
GO

ALTER TABLE CODIGO_ENIGMA.PROVEEDOR ADD CONSTRAINT FK_PROVEEDOR_LOCALIDAD_CODIGO FOREIGN KEY(LOCALIDAD_CODIGO) REFERENCES CODIGO_ENIGMA.LOCALIDAD
GO
   	
ALTER TABLE CODIGO_ENIGMA.COMPRA
ADD CONSTRAINT FK_PROVEEDOR_CODIGO FOREIGN KEY(PROVEEDOR_CODIGO) REFERENCES CODIGO_ENIGMA.PROVEEDOR,
   	CONSTRAINT FK_DESCUENTO_COMPRA_CODIGO FOREIGN KEY(DESCUENTO_COMPRA_CODIGO) REFERENCES CODIGO_ENIGMA.DESCUENTO_COMPRA,
	CONSTRAINT FK_C_MEDIO_PAGO_CODIGO FOREIGN KEY(MEDIO_PAGO_CODIGO) REFERENCES CODIGO_ENIGMA.MEDIO_PAGO
GO

ALTER TABLE CODIGO_ENIGMA.COMPRAxPRODUCTO
ADD CONSTRAINT FK_COMPRA_NUMERO FOREIGN KEY(COMPRA_NUMERO) REFERENCES CODIGO_ENIGMA.COMPRA,
   	CONSTRAINT FK_CP_PRODUCTO_VARIANTE_CODIGO FOREIGN KEY(PRODUCTO_VARIANTE_CODIGO) REFERENCES CODIGO_ENIGMA.PRODUCTO_VARIANTE
GO

ALTER TABLE CODIGO_ENIGMA.PRODUCTO
ADD CONSTRAINT FK_PRODUCTO_CATEGORIA_CODIGO FOREIGN KEY(PRODUCTO_CATEGORIA_CODIGO) REFERENCES CODIGO_ENIGMA.PRODUCTO_CATEGORIA
GO

ALTER TABLE CODIGO_ENIGMA.PRODUCTO_VARIANTE
ADD CONSTRAINT FK_TIPO_VARIANTE_CODIGO FOREIGN KEY(TIPO_VARIANTE_CODIGO) REFERENCES CODIGO_ENIGMA.TIPO_VARIANTE,
	CONSTRAINT FK_PRODUCTO_CODIGO FOREIGN KEY(PRODUCTO_CODIGO) REFERENCES CODIGO_ENIGMA.PRODUCTO
GO

ALTER TABLE CODIGO_ENIGMA.CLIENTE ADD CONSTRAINT FK_CLIENTE_LOCALIDAD_CODIGO FOREIGN KEY(LOCALIDAD_CODIGO) REFERENCES CODIGO_ENIGMA.LOCALIDAD
GO

ALTER TABLE CODIGO_ENIGMA.VENTAxPRODUCTO
ADD CONSTRAINT FK_VP_PRODUCTO_VARIANTE_CODIGO FOREIGN KEY(PRODUCTO_VARIANTE_CODIGO) REFERENCES CODIGO_ENIGMA.PRODUCTO_VARIANTE,
	CONSTRAINT FK_VENTA_CODIGO FOREIGN KEY(VENTA_CODIGO) REFERENCES CODIGO_ENIGMA.VENTA
GO

ALTER TABLE CODIGO_ENIGMA.VENTA
ADD CONSTRAINT FK_CLIENTE_CODIGO FOREIGN KEY(CLIENTE_CODIGO) REFERENCES CODIGO_ENIGMA.CLIENTE,
   	CONSTRAINT FK_MEDIO_PAGO_VENTA_CODIGO FOREIGN KEY(MEDIO_PAGO_VENTA_CODIGO) REFERENCES CODIGO_ENIGMA.MEDIO_PAGO_VENTA,
	CONSTRAINT FK_CANAL_VENTA_CODIGO FOREIGN KEY(CANAL_VENTA_CODIGO) REFERENCES CODIGO_ENIGMA.CANAL_VENTA,
	CONSTRAINT FK_MEDIO_ENVIO_VENTA_CODIGO FOREIGN KEY(MEDIO_ENVIO_VENTA_CODIGO) REFERENCES CODIGO_ENIGMA.MEDIO_ENVIO_VENTA
GO

ALTER TABLE CODIGO_ENIGMA.CUPONxVENTA
ADD CONSTRAINT FK_VENTA_CUPON_CODIGO FOREIGN KEY(VENTA_CUPON_CODIGO) REFERENCES CODIGO_ENIGMA.VENTA_CUPON,
	CONSTRAINT FK_CV_VENTA_CODIGO FOREIGN KEY(VENTA_CODIGO) REFERENCES CODIGO_ENIGMA.VENTA
GO

ALTER TABLE CODIGO_ENIGMA.MEDIO_ENVIO_VENTA
ADD CONSTRAINT FK_MEDIO_ENVIO_CODIGO FOREIGN KEY(MEDIO_ENVIO_CODIGO) REFERENCES CODIGO_ENIGMA.MEDIO_ENVIO,
	CONSTRAINT FK_LOCALIDAD_CODIGO FOREIGN KEY(LOCALIDAD_CODIGO) REFERENCES CODIGO_ENIGMA.LOCALIDAD
GO

ALTER TABLE CODIGO_ENIGMA.DESCUENTO_VENTA
ADD CONSTRAINT FK_DES_VENTA_CODIGO FOREIGN KEY(VENTA_CODIGO) REFERENCES CODIGO_ENIGMA.VENTA,
	CONSTRAINT FK_TIPO_DESCUENTO_CODIGO FOREIGN KEY(TIPO_DESCUENTO_CODIGO) REFERENCES CODIGO_ENIGMA.TIPO_DESCUENTO
GO

ALTER TABLE CODIGO_ENIGMA.CANAL_VENTA ADD CONSTRAINT FK_CANAL_CODIGO FOREIGN KEY(CANAL_CODIGO) REFERENCES CODIGO_ENIGMA.CANAL
GO

ALTER TABLE CODIGO_ENIGMA.MEDIO_PAGO_VENTA ADD CONSTRAINT FK_MPV_MEDIO_PAGO_CODIGO FOREIGN KEY(MEDIO_PAGO_CODIGO) REFERENCES CODIGO_ENIGMA.MEDIO_PAGO
GO



--CREACION FUNCIONES

--OBTENER PROVINCIA CODIGO
CREATE FUNCTION CODIGO_ENIGMA.OBTENER_PROVINCIA_CODIGO(@PROVINCIA nvarchar(255))
RETURNS INT
AS
BEGIN 
  DECLARE @CODIGO as int
  SELECT DISTINCT @CODIGO = PROVINCIA_CODIGO FROM CODIGO_ENIGMA.PROVINCIA
  WHERE @PROVINCIA = PROVINCIA_NOMBRE
  RETURN @CODIGO
END 
GO 

--2 OBTENER LOCALIDAD CODIGO
CREATE FUNCTION CODIGO_ENIGMA.OBTENER_LOCALIDAD_CODIGO(@LOCALIDAD nvarchar(50),@CODIGO_POSTAL DECIMAL(18,0))
RETURNS INT 
AS
BEGIN 
  DECLARE @CODIGO as int
  SELECT DISTINCT @CODIGO = LOCALIDAD_CODIGO FROM CODIGO_ENIGMA.LOCALIDAD
  WHERE @LOCALIDAD = LOCALIDAD_NOMBRE
  and @CODIGO_POSTAL = LOCALIDAD_CODIGO_POSTAL
  RETURN @CODIGO
END 
GO 

--3 OBTENER PROVEEDOR CODIGO
CREATE FUNCTION CODIGO_ENIGMA.OBTENER_PROVEEDOR_CODIGO(@RAZONSOCIAL nvarchar(50), @CUIT nvarchar(50))
RETURNS INT 
AS
BEGIN 
  DECLARE @CODIGO as int
  SELECT DISTINCT @CODIGO = PROVEEDOR_CODIGO FROM CODIGO_ENIGMA.PROVEEDOR
  WHERE @RAZONSOCIAL = PROVEEDOR_RAZON_SOCIAL
  AND @CUIT = PROVEEDOR_CUIT
  RETURN @CODIGO
END 
GO 

--4 OBTENER MEDIO PAGO CODIGO
CREATE FUNCTION CODIGO_ENIGMA.OBTENER_MEDIO_PAGO_CODIGO(@MEDIO_PAGO nvarchar(255))
RETURNS INT 
AS
BEGIN 
  DECLARE @CODIGO as int
  SELECT DISTINCT @CODIGO = MEDIO_PAGO_CODIGO FROM CODIGO_ENIGMA.MEDIO_PAGO
  WHERE @MEDIO_PAGO = MEDIO_PAGO
  RETURN @CODIGO
END 
GO 

--5 OBTENER TIPO VARIANTE
CREATE FUNCTION CODIGO_ENIGMA.OBTENER_TIPO_VARIANTE_CODIGO(@VARIANTE nvarchar(50))
RETURNS INT 
AS
BEGIN 
  DECLARE @CODIGO as int
  SELECT DISTINCT @CODIGO = TIPO_VARIANTE_CODIGO FROM CODIGO_ENIGMA.TIPO_VARIANTE
  WHERE @VARIANTE = PRODUCTO_TIPO_VARIANTE
  RETURN @CODIGO
END 
GO 

--6 OBTENER PRODUCTO CATEGORIA CODIGO
CREATE FUNCTION CODIGO_ENIGMA.OBTENER_PRODUCTO_CATEGORIA_CODIGO(@CATEGORIA nvarchar(255))
RETURNS INT 
AS
BEGIN 
  DECLARE @CODIGO as int
  SELECT DISTINCT @CODIGO = PRODUCTO_CATEGORIA_CODIGO FROM CODIGO_ENIGMA.PRODUCTO_CATEGORIA
  WHERE @CATEGORIA = PRODUCTO_CATEGORIA
  RETURN @CODIGO
END 
GO


--7 OBTENER DESCUENTO COMPRA CODIGO

CREATE FUNCTION CODIGO_ENIGMA.OBTENER_DESCUENTO_COMPRA_CODIGO(@VALOR decimal(18,2))
RETURNS INT 
AS
BEGIN 
  DECLARE @CODIGO as int
  SELECT DISTINCT @CODIGO = DESCUENTO_COMPRA_CODIGO FROM CODIGO_ENIGMA.DESCUENTO_COMPRA
  WHERE @VALOR = DESCUENTO_COMPRA_VALOR
  RETURN @CODIGO
END 
GO

--8 OBTENER TIPO DESCUENTO CODIGO
CREATE FUNCTION CODIGO_ENIGMA.OBTENER_TIPO_DESCUENTO_CODIGO(@VENTA_DESCUENTO nvarchar(255))
RETURNS INT 
AS
BEGIN 
  DECLARE @CODIGO as int
  SELECT DISTINCT @CODIGO = TIPO_DESCUENTO_CODIGO FROM CODIGO_ENIGMA.TIPO_DESCUENTO
  WHERE @VENTA_DESCUENTO = VENTA_DESCUENTO_CONCEPTO
  RETURN @CODIGO
END 
GO

--9 OBTENER MEDIO ENVIO CODIGO
CREATE FUNCTION CODIGO_ENIGMA.OBTENER_MEDIO_ENVIO_CODIGO(@VENTA_MEDIO nvarchar(255))
RETURNS INT 
AS
BEGIN 
  DECLARE @CODIGO as int
  SELECT DISTINCT @CODIGO = MEDIO_ENVIO_CODIGO FROM CODIGO_ENIGMA.MEDIO_ENVIO
  WHERE @VENTA_MEDIO = VENTA_MEDIO_ENVIO
  RETURN @CODIGO
END 
GO

--10 OBTENER CANAL CODIGO
CREATE FUNCTION CODIGO_ENIGMA.OBTENER_CANAL_CODIGO(@VENTA_CANAL nvarchar(255))
RETURNS INT 
AS
BEGIN 
  DECLARE @CODIGO as int
  SELECT DISTINCT @CODIGO = CANAL_CODIGO FROM CODIGO_ENIGMA.CANAL
  WHERE @VENTA_CANAL = VENTA_CANAL
  RETURN @CODIGO
END
GO

--10 OBTENER CLIENTE CODIGO
CREATE FUNCTION CODIGO_ENIGMA.OBTENER_CLIENTE_CODIGO(@DNI decimal(18,0), @MAIL nvarchar(255))
RETURNS INT 
AS
BEGIN 
  DECLARE @CODIGO as int
  SELECT DISTINCT @CODIGO = CLIENTE_CODIGO FROM CODIGO_ENIGMA.CLIENTE
  WHERE @DNI = CLIENTE_DNI
  and @MAIL = CLIENTE_MAIL
  RETURN @CODIGO
END 
GO

--11 OBTENER MEDIO ENVIO VENTA CODIGO
CREATE FUNCTION CODIGO_ENIGMA.OBTENER_MEDIO_ENVIO_VENTA_CODIGO(@PRECIO decimal(18,2), @LOCALIDAD nvarchar(50),@CODIGO_POSTAL DECIMAL(18,0))
RETURNS INT 
AS
BEGIN 
  DECLARE @CODIGO as int
  DECLARE @LOCALIDAD_CODIGO as int = CODIGO_ENIGMA.OBTENER_LOCALIDAD_CODIGO(@LOCALIDAD, @CODIGO_POSTAL)

  SELECT DISTINCT @CODIGO = MEDIO_ENVIO_VENTA_CODIGO FROM CODIGO_ENIGMA.MEDIO_ENVIO_VENTA
  WHERE @PRECIO = VENTA_ENVIO_PRECIO
  and @LOCALIDAD_CODIGO = LOCALIDAD_CODIGO
  RETURN @CODIGO
END 
GO

--12 OBTENER MEDIO PAGO VENTA CODIGO
CREATE FUNCTION CODIGO_ENIGMA.OBTENER_MEDIO_PAGO_VENTA_CODIGO(@MEDIO nvarchar(255))
RETURNS INT 
AS
BEGIN 
  DECLARE @CODIGO as int
  DECLARE @MEDIO_PAGO_CODIGO as int = CODIGO_ENIGMA.OBTENER_MEDIO_PAGO_CODIGO(@MEDIO)

  SELECT DISTINCT @CODIGO = MEDIO_PAGO_VENTA_CODIGO FROM CODIGO_ENIGMA.MEDIO_PAGO_VENTA
  WHERE @MEDIO_PAGO_CODIGO = MEDIO_PAGO_CODIGO
  RETURN @CODIGO
END 
GO

--13 OBTENER CANAL VENTA CODIGO
CREATE FUNCTION CODIGO_ENIGMA.OBTENER_CANAL_VENTA_CODIGO(@CANAL nvarchar(255))
RETURNS INT 
AS
BEGIN 
  DECLARE @CODIGO as int
  DECLARE @CANAL_CODIGO as int = CODIGO_ENIGMA.OBTENER_CANAL_CODIGO(@CANAL)

  SELECT DISTINCT @CODIGO = CANAL_VENTA_CODIGO FROM CODIGO_ENIGMA.CANAL_VENTA
  WHERE @CANAL_CODIGO = CANAL_CODIGO 
  RETURN @CODIGO
END 
GO

--14 OBTENER PRODUCTO VARIANTE CODIGO
CREATE FUNCTION CODIGO_ENIGMA.OBTENER_PRODUCTO_VARIANTE_CODIGO(@PROD_VAR_ID nvarchar(255), @PRECIO decimal(18,2))
RETURNS INT 
AS
BEGIN 
  DECLARE @CODIGO as int
  SELECT DISTINCT @CODIGO = PRODUCTO_VARIANTE_CODIGO FROM CODIGO_ENIGMA.PRODUCTO_VARIANTE
  WHERE @PROD_VAR_ID = PRODUCTO_VARIANTE_ID
  AND @PRECIO = PRODUCTO_VARIANTE_PRECIO
  RETURN @CODIGO
END  
GO


--CREACION PROCEDURES

--1 MIGRACION PROVINCIAS
CREATE PROCEDURE CODIGO_ENIGMA.migrar_provincia
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.PROVINCIA(PROVINCIA_NOMBRE)
   	(SELECT DISTINCT CLIENTE_PROVINCIA
   	FROM gd_esquema.Maestra
	WHERE CLIENTE_PROVINCIA is not null) 
	UNION
	(SELECT DISTINCT PROVEEDOR_PROVINCIA
	FROM gd_esquema.Maestra
	WHERE PROVEEDOR_PROVINCIA is not null)
 END
 GO

 -- 2 MIGRACION LOCALIDADES
CREATE PROCEDURE CODIGO_ENIGMA.migrar_localidad
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.LOCALIDAD(LOCALIDAD_NOMBRE, LOCALIDAD_CODIGO_POSTAL, PROVINCIA_CODIGO)
   	(SELECT DISTINCT CLIENTE_LOCALIDAD, CLIENTE_CODIGO_POSTAL, CODIGO_ENIGMA.OBTENER_PROVINCIA_CODIGO(CLIENTE_PROVINCIA)
	FROM gd_esquema.Maestra
	WHERE CLIENTE_LOCALIDAD is not null)
	UNION
	(SELECT DISTINCT PROVEEDOR_LOCALIDAD, PROVEEDOR_CODIGO_POSTAL, CODIGO_ENIGMA.OBTENER_PROVINCIA_CODIGO(PROVEEDOR_PROVINCIA)
	FROM gd_esquema.Maestra
	WHERE PROVEEDOR_LOCALIDAD is not null)
 END
 GO


--3 MIGRACION PROOVEDORES
CREATE PROCEDURE CODIGO_ENIGMA.migrar_proveedor
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.PROVEEDOR(PROVEEDOR_RAZON_SOCIAL, PROVEEDOR_CUIT, PROVEEDOR_DOMICILIO, PROVEEDOR_MAIL, LOCALIDAD_CODIGO)
   	SELECT DISTINCT PROVEEDOR_RAZON_SOCIAL, PROVEEDOR_CUIT, PROVEEDOR_DOMICILIO, PROVEEDOR_MAIL, CODIGO_ENIGMA.OBTENER_LOCALIDAD_CODIGO(PROVEEDOR_LOCALIDAD, PROVEEDOR_CODIGO_POSTAL)
   	FROM gd_esquema.Maestra
	WHERE PROVEEDOR_RAZON_SOCIAL is not null
 END
 GO

 
--4 MIGRACION DESCUENTO_COMPRAS
CREATE PROCEDURE CODIGO_ENIGMA.migrar_descuento_compra
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.DESCUENTO_COMPRA(DESCUENTO_COMPRA_CODIGO,DESCUENTO_COMPRA_VALOR)
   	SELECT DISTINCT DESCUENTO_COMPRA_CODIGO, DESCUENTO_COMPRA_VALOR
   	FROM gd_esquema.Maestra 
	WHERE DESCUENTO_COMPRA_CODIGO is not NULL
 END
 GO


 --5 MIGRACION MEDIO_PAGOS
CREATE PROCEDURE CODIGO_ENIGMA.migrar_medio_pago
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.MEDIO_PAGO(MEDIO_PAGO)
   	(SELECT DISTINCT VENTA_MEDIO_PAGO
   	FROM gd_esquema.Maestra 
	WHERE VENTA_MEDIO_PAGO is not null)
	UNION
	(SELECT DISTINCT COMPRA_MEDIO_PAGO
   	FROM gd_esquema.Maestra 
	WHERE COMPRA_MEDIO_PAGO is not null)
 END
 GO


--6 MIGRACION TIPO_VARIANTE 
CREATE PROCEDURE CODIGO_ENIGMA.migrar_tipo_variante
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.TIPO_VARIANTE(PRODUCTO_TIPO_VARIANTE)
   	SELECT DISTINCT PRODUCTO_TIPO_VARIANTE
   	FROM gd_esquema.Maestra
	WHERE PRODUCTO_TIPO_VARIANTE is not null
 END
 GO


--7 MIGRACION PRODUCTO_CATEGORIAS 
CREATE PROCEDURE CODIGO_ENIGMA.migrar_producto_categoria
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.PRODUCTO_CATEGORIA(PRODUCTO_CATEGORIA)
   	SELECT DISTINCT PRODUCTO_CATEGORIA
   	FROM gd_esquema.Maestra
	WHERE PRODUCTO_CATEGORIA is not null
 END
 GO

 
--8 MIGRACION PRODUCTOS
CREATE PROCEDURE CODIGO_ENIGMA.migrar_producto
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.PRODUCTO(PRODUCTO_CODIGO, PRODUCTO_NOMBRE, PRODUCTO_DESCRIPCION, PRODUCTO_MARCA, PRODUCTO_MATERIAL, PRODUCTO_CATEGORIA_CODIGO)
   	SELECT DISTINCT PRODUCTO_CODIGO, PRODUCTO_NOMBRE, PRODUCTO_DESCRIPCION, PRODUCTO_MARCA, PRODUCTO_MATERIAL, CODIGO_ENIGMA.OBTENER_PRODUCTO_CATEGORIA_CODIGO(PRODUCTO_CATEGORIA)
   	FROM gd_esquema.Maestra 
	where PRODUCTO_CODIGO is not null
 END
 GO


 --9 MIGRACION PRODUCTO VARIANTES
CREATE PROCEDURE CODIGO_ENIGMA.migrar_producto_variante
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.PRODUCTO_VARIANTE(PRODUCTO_VARIANTE_ID, PRODUCTO_VARIANTE, TIPO_VARIANTE_CODIGO, PRODUCTO_CODIGO, PRODUCTO_VARIANTE_PRECIO)
	(SELECT DISTINCT PRODUCTO_VARIANTE_CODIGO, PRODUCTO_VARIANTE, CODIGO_ENIGMA.OBTENER_TIPO_VARIANTE_CODIGO(PRODUCTO_TIPO_VARIANTE), PRODUCTO_CODIGO, COMPRA_PRODUCTO_PRECIO
   	FROM gd_esquema.Maestra 
	where PRODUCTO_VARIANTE_CODIGO is not null
	AND COMPRA_NUMERO is not null)--15716 precio compra
	UNION
	(SELECT DISTINCT PRODUCTO_VARIANTE_CODIGO, PRODUCTO_VARIANTE, CODIGO_ENIGMA.OBTENER_TIPO_VARIANTE_CODIGO(PRODUCTO_TIPO_VARIANTE), PRODUCTO_CODIGO, VENTA_PRODUCTO_PRECIO
   	FROM gd_esquema.Maestra 
	where PRODUCTO_VARIANTE_CODIGO is not null
	AND VENTA_CODIGO is not null)--15704 precio venta
 END
 GO


 --10 MIGRACION COMPRAS
 CREATE PROCEDURE CODIGO_ENIGMA.migrar_compra
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.COMPRA(COMPRA_NUMERO, COMPRA_FECHA, COMPRA_TOTAL, PROVEEDOR_CODIGO, MEDIO_PAGO_CODIGO, DESCUENTO_COMPRA_CODIGO)
   	SELECT DISTINCT compra_numero, COMPRA_FECHA, 
	COMPRA_TOTAL, 
	CODIGO_ENIGMA.obtener_proveedor_codigo(PROVEEDOR_RAZON_SOCIAL, PROVEEDOR_CUIT),
	 CODIGO_ENIGMA.OBTENER_MEDIO_PAGO_CODIGO(compra_MEDIO_PAGO), 
	 CODIGO_ENIGMA.OBTENER_DESCUENTO_COMPRA_CODIGO(DESCUENTO_COMPRA_VALOR)
	from gd_esquema.Maestra
	where (DESCUENTO_COMPRA_CODIGO is not NULL and COMPRA_NUMERO is not null)
 END
 GO


--11 MIGRACION COMPRAxPRODUCTOS
CREATE PROCEDURE CODIGO_ENIGMA.migrar_CompraxProducto
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.COMPRAxPRODUCTO(COMPRA_PRODUCTO_CANTIDAD, COMPRA_NUMERO, PRODUCTO_VARIANTE_CODIGO)
   	SELECT DISTINCT COMPRA_PRODUCTO_CANTIDAD, COMPRA_NUMERO, CODIGO_ENIGMA.OBTENER_PRODUCTO_VARIANTE_CODIGO(PRODUCTO_VARIANTE_CODIGO, COMPRA_PRODUCTO_PRECIO)
   	FROM gd_esquema.Maestra 
	WHERE (COMPRA_NUMERO is not null and PRODUCTO_VARIANTE_CODIGO is not null )
 END
 GO


--12 MIGRACION CLIENTES
CREATE PROCEDURE CODIGO_ENIGMA.migrar_cliente
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.CLIENTE(CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_DNI, CLIENTE_DIRECCION, CLIENTE_TELEFONO, CLIENTE_MAIL, CLIENTE_FECHA_NAC, LOCALIDAD_CODIGO)
   	SELECT DISTINCT CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_DNI, CLIENTE_DIRECCION, CLIENTE_TELEFONO, CLIENTE_MAIL, CLIENTE_FECHA_NAC, CODIGO_ENIGMA.OBTENER_LOCALIDAD_CODIGO(CLIENTE_LOCALIDAD, CLIENTE_CODIGO_POSTAL)
   	FROM gd_esquema.Maestra
	WHERE CLIENTE_NOMBRE is not null
 END
 GO

 --13 MIGRACION MEDIO_ENVIO
CREATE PROCEDURE CODIGO_ENIGMA.migrar_medio_envio
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.MEDIO_ENVIO(VENTA_MEDIO_ENVIO)
   	SELECT DISTINCT VENTA_MEDIO_ENVIO
   	FROM gd_esquema.Maestra 
	WHERE VENTA_MEDIO_ENVIO is not null
 END
 GO

  --14 MIGRACION MEDIO_ENVIO_VENTA               VENTA_ENVIO_TIEMPO queda nulo para completarse a futuro
CREATE PROCEDURE CODIGO_ENIGMA.migrar_medio_envio_venta
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.MEDIO_ENVIO_VENTA(VENTA_ENVIO_PRECIO, MEDIO_ENVIO_CODIGO, LOCALIDAD_CODIGO)
   	SELECT DISTINCT VENTA_ENVIO_PRECIO, CODIGO_ENIGMA.OBTENER_MEDIO_ENVIO_CODIGO(VENTA_MEDIO_ENVIO), CODIGO_ENIGMA.OBTENER_LOCALIDAD_CODIGO(CLIENTE_LOCALIDAD, CLIENTE_CODIGO_POSTAL)
   	FROM gd_esquema.Maestra 
	WHERE VENTA_ENVIO_PRECIO is not null
 END
 GO

  --15 MIGRACION MEDIO_PAGO_VENTA
CREATE PROCEDURE CODIGO_ENIGMA.migrar_medio_pago_venta
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.MEDIO_PAGO_VENTA(VENTA_MEDIO_PAGO_COSTO, MEDIO_PAGO_CODIGO)
   	SELECT DISTINCT VENTA_MEDIO_PAGO_COSTO, CODIGO_ENIGMA.OBTENER_MEDIO_PAGO_CODIGO(VENTA_MEDIO_PAGO)
   	FROM gd_esquema.Maestra 
	WHERE VENTA_MEDIO_PAGO_COSTO is not null
 END
 GO

  --16 MIGRACION CANAL
CREATE PROCEDURE CODIGO_ENIGMA.MIGRAR_CANAL
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.CANAL(VENTA_CANAL)
   	SELECT DISTINCT VENTA_CANAL
   	FROM gd_esquema.Maestra
	WHERE VENTA_CANAL is not null
 END
 GO

   --17 MIGRACION CANAL VENTA
CREATE PROCEDURE CODIGO_ENIGMA.MIGRAR_CANAL_VENTA
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.CANAL_VENTA(VENTA_CANAL_COSTO, CANAL_CODIGO)
   	SELECT DISTINCT VENTA_CANAL_COSTO, CODIGO_ENIGMA.OBTENER_CANAL_CODIGO(VENTA_CANAL)
   	FROM gd_esquema.Maestra 
	WHERE VENTA_CANAL_COSTO is not null
 END
 GO

    --18 MIGRACION VENTA
CREATE PROCEDURE CODIGO_ENIGMA.MIGRAR_VENTA
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.VENTA(VENTA_CODIGO, VENTA_FECHA, VENTA_TOTAL, CLIENTE_CODIGO, MEDIO_PAGO_VENTA_CODIGO, CANAL_VENTA_CODIGO, MEDIO_ENVIO_VENTA_CODIGO)
   	SELECT DISTINCT VENTA_CODIGO, VENTA_FECHA, VENTA_TOTAL, CODIGO_ENIGMA.OBTENER_CLIENTE_CODIGO(CLIENTE_DNI, CLIENTE_MAIL), CODIGO_ENIGMA.OBTENER_MEDIO_PAGO_VENTA_CODIGO(VENTA_MEDIO_PAGO), CODIGO_ENIGMA.OBTENER_CANAL_VENTA_CODIGO(VENTA_CANAL), CODIGO_ENIGMA.OBTENER_MEDIO_ENVIO_VENTA_CODIGO(VENTA_ENVIO_PRECIO, CLIENTE_LOCALIDAD, CLIENTE_CODIGO_POSTAL)
   	FROM gd_esquema.Maestra 
	WHERE VENTA_CODIGO is not null
 END
 GO

 -- 19 MIGRACION VENTAxPRODUCTOS
CREATE PROCEDURE CODIGO_ENIGMA.migrar_VentaxProducto
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.VENTAxPRODUCTO(PRODUCTO_VARIANTE_CODIGO, VENTA_PRODUCTO_CANTIDAD, VENTA_CODIGO)
   	SELECT DISTINCT CODIGO_ENIGMA.OBTENER_PRODUCTO_VARIANTE_CODIGO(PRODUCTO_VARIANTE_CODIGO, VENTA_PRODUCTO_PRECIO), VENTA_PRODUCTO_CANTIDAD, VENTA_CODIGO
   	FROM gd_esquema.Maestra 
	WHERE (VENTA_CODIGO is not null and PRODUCTO_VARIANTE_CODIGO is not null )
 END
 GO

 
 -- 20 MIGRACION VENTA CUPON
CREATE PROCEDURE CODIGO_ENIGMA.MIGRAR_venta_cupon
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.VENTA_CUPON(VENTA_CUPON_CODIGO, VENTA_CUPON_FECHA_DESDE, VENTA_CUPON_FECHA_HASTA, VENTA_CUPON_VALOR, VENTA_CUPON_TIPO)
   	SELECT DISTINCT VENTA_CUPON_CODIGO, VENTA_CUPON_FECHA_DESDE, VENTA_CUPON_FECHA_HASTA, VENTA_CUPON_VALOR, VENTA_CUPON_TIPO
   	FROM gd_esquema.Maestra
	WHERE VENTA_CUPON_CODIGO is not null
 END
 GO


 -- 21 MIGRACION CUPONXVENTA
CREATE PROCEDURE CODIGO_ENIGMA.MIGRAR_CuponxVenta
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.CUPONXVENTA(VENTA_CUPON_CODIGO, VENTA_CODIGO, VENTA_CUPON_IMPORTE)
   	SELECT VENTA_CUPON_CODIGO, VENTA_CODIGO, VENTA_CUPON_IMPORTE
   	FROM gd_esquema.Maestra 
	WHERE VENTA_CUPON_CODIGO IS NOT NULL AND VENTA_CODIGO IS NOT NULL 
 END
 GO
 


  -- 22 MIGRACION TIPO DESCUENTO
CREATE PROCEDURE CODIGO_ENIGMA.MIGRAR_TIPO_DESCUENTO
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.TIPO_DESCUENTO(VENTA_DESCUENTO_CONCEPTO)
   	SELECT DISTINCT VENTA_DESCUENTO_CONCEPTO
   	FROM gd_esquema.Maestra 
	WHERE VENTA_DESCUENTO_CONCEPTO IS NOT NULL 
 END
 GO

   -- 23 MIGRACION DESCUENTO VENTA
CREATE PROCEDURE CODIGO_ENIGMA.MIGRAR_DESCUENTO_VENTA
  AS
  BEGIN
   	INSERT INTO CODIGO_ENIGMA.DESCUENTO_VENTA(VENTA_DESCUENTO_IMPORTE, VENTA_CODIGO, TIPO_DESCUENTO_CODIGO)
   	SELECT VENTA_DESCUENTO_IMPORTE, VENTA_CODIGO, CODIGO_ENIGMA.OBTENER_TIPO_DESCUENTO_CODIGO(VENTA_DESCUENTO_CONCEPTO)
   	FROM gd_esquema.Maestra 
	WHERE VENTA_DESCUENTO_CONCEPTO IS NOT NULL 
 END
 GO
 
 --EXEC PROCEDURES

 exec codigo_enigma.migrar_provincia
 exec codigo_enigma.migrar_localidad
 exec codigo_enigma.migrar_proveedor
 exec codigo_enigma.migrar_descuento_compra
 exec codigo_enigma.migrar_medio_pago
 exec codigo_enigma.migrar_tipo_variante
 exec codigo_enigma.migrar_producto_categoria
 exec codigo_enigma.migrar_producto
 exec codigo_enigma.migrar_producto_variante
 exec codigo_enigma.migrar_compra
 exec codigo_enigma.migrar_CompraxProducto
 exec codigo_enigma.migrar_cliente
 exec CODIGO_ENIGMA.migrar_medio_envio
 exec CODIGO_ENIGMA.migrar_medio_envio_venta
 exec CODIGO_ENIGMA.migrar_medio_pago_venta
 exec CODIGO_ENIGMA.MIGRAR_CANAL
 exec CODIGO_ENIGMA.MIGRAR_CANAL_VENTA
 exec CODIGO_ENIGMA.MIGRAR_VENTA
 exec CODIGO_ENIGMA.migrar_VentaxProducto
 exec CODIGO_ENIGMA.MIGRAR_venta_cupon
 exec CODIGO_ENIGMA.MIGRAR_CuponxVenta
 exec CODIGO_ENIGMA.MIGRAR_TIPO_DESCUENTO
 exec CODIGO_ENIGMA.MIGRAR_DESCUENTO_VENTA
