use GD2C2022

--DROPS FK

IF OBJECT_ID('BI_CODIGO_ENIGMA.FK_D_TIPO_DESCUENTO_CODIGO', 'F') IS NOT NULL
  ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_DESCUENTO DROP CONSTRAINT FK_D_TIPO_DESCUENTO_CODIGO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.FK_D_CANAL_VENTA_CODIGO', 'F') IS NOT NULL
  ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_DESCUENTO DROP CONSTRAINT FK_D_CANAL_VENTA_CODIGO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.FK_D_DIM_TIEMPO_CODIGO', 'F') IS NOT NULL
  ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_DESCUENTO DROP CONSTRAINT FK_D_DIM_TIEMPO_CODIGO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.FK_D_DIM_MEDIO_PAGO', 'F') IS NOT NULL
  ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_DESCUENTO DROP CONSTRAINT FK_D_DIM_MEDIO_PAGO_CODIGO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.FK_C_PROVEEDOR_CODIGO', 'F') IS NOT NULL
  ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_COMPRA_PRODUCTO DROP CONSTRAINT FK_C_PROVEEDOR_CODIGO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.FK_C_PRODUCTO_VARIANTE_CODIGO', 'F') IS NOT NULL
  ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_COMPRA_PRODUCTO DROP CONSTRAINT FK_C_PRODUCTO_VARIANTE_CODIGO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.FK_C_DIM_TIEMPO_CODIGO', 'F') IS NOT NULL
  ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_COMPRA_PRODUCTO DROP CONSTRAINT FK_C_DIM_TIEMPO_CODIGO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.FK_C_COMPRA_NUMERO', 'F') IS NOT NULL
  ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_COMPRA_PRODUCTO DROP CONSTRAINT FK_C_COMPRA_NUMERO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.FK_V_MEDIO_PAGO_CODIGO', 'F') IS NOT NULL
  ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO DROP CONSTRAINT FK_V_MEDIO_PAGO_CODIGO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.FK_V_PROVEEDOR_CODIGO', 'F') IS NOT NULL
  ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO DROP CONSTRAINT FK_V_PROVEEDOR_CODIGO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.FK_V_DIM_TIEMPO_CODIGO', 'F') IS NOT NULL
  ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO DROP CONSTRAINT FK_V_DIM_TIEMPO_CODIGO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.FK_V_MEDIO_ENVIO_CODIGO', 'F') IS NOT NULL
  ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO DROP CONSTRAINT FK_V_MEDIO_ENVIO_CODIGO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.FK_V_RANGO_ETARIO', 'F') IS NOT NULL
  ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO DROP CONSTRAINT FK_V_RANGO_ETARIO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.FK_V_CANAL_VENTA_CODIGO', 'F') IS NOT NULL
  ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO DROP CONSTRAINT FK_V_CANAL_VENTA_CODIGO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.FK_V_PROVINCIA_CODIGO', 'F') IS NOT NULL
  ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO DROP CONSTRAINT FK_V_PROVINCIA_CODIGO
GO



--DROPEO PREVENTIVO DE FUNCIONES AUXILIARES


IF OBJECT_ID('BI_CODIGO_ENIGMA.OBTENER_RANGO_ETARIO') IS NOT NULL
	DROP FUNCTION BI_CODIGO_ENIGMA.OBTENER_RANGO_ETARIO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.OBTENER_DIM_TIEMPO_CODIGO') IS NOT NULL
	DROP FUNCTION BI_CODIGO_ENIGMA.OBTENER_DIM_TIEMPO_CODIGO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.OBTENER_TIPO_DESCUENTO_CODIGO') IS NOT NULL
	DROP FUNCTION BI_CODIGO_ENIGMA.OBTENER_TIPO_DESCUENTO_CODIGO
GO
 
-- DROPEO DE DIMENSIONES Y HECHOS

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO', 'U') IS NOT NULL
  DROP TABLE BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_HECHO_COMPRA_PRODUCTO', 'U') IS NOT NULL
  DROP TABLE BI_CODIGO_ENIGMA.BI_HECHO_COMPRA_PRODUCTO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_HECHO_DESCUENTO', 'U') IS NOT NULL
  DROP TABLE BI_CODIGO_ENIGMA.BI_HECHO_DESCUENTO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_DIM_PROVINCIA', 'U') IS NOT NULL
  DROP TABLE BI_CODIGO_ENIGMA.BI_DIM_PROVINCIA
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_DIM_TIEMPO', 'U') IS NOT NULL
  DROP TABLE BI_CODIGO_ENIGMA.BI_DIM_TIEMPO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_DIM_RANGO_ETARIO_CLIENTE', 'U') IS NOT NULL
  DROP TABLE BI_CODIGO_ENIGMA.BI_DIM_RANGO_ETARIO_CLIENTE
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_DIM_CANAL_VENTA', 'U') IS NOT NULL
  DROP TABLE BI_CODIGO_ENIGMA.BI_DIM_CANAL_VENTA
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_DIM_MEDIO_PAGO', 'U') IS NOT NULL
  DROP TABLE BI_CODIGO_ENIGMA.BI_DIM_MEDIO_PAGO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_DIM_PRODUCTO_CATEGORIA', 'U') IS NOT NULL
  DROP TABLE BI_CODIGO_ENIGMA.BI_DIM_PRODUCTO_CATEGORIA
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_DIM_PRODUCTO_VARIANTE', 'U') IS NOT NULL
  DROP TABLE BI_CODIGO_ENIGMA.BI_DIM_PRODUCTO_VARIANTE
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_DIM_TIPO_DESCUENTO', 'U') IS NOT NULL
  DROP TABLE BI_CODIGO_ENIGMA.BI_DIM_TIPO_DESCUENTO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_DIM_TIPO_ENVIO', 'U') IS NOT NULL
  DROP TABLE BI_CODIGO_ENIGMA.BI_DIM_TIPO_ENVIO
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_DIM_PROVEEDOR', 'U') IS NOT NULL
  DROP TABLE BI_CODIGO_ENIGMA.BI_DIM_PROVEEDOR
GO

--DROPS PROCEDURES

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_MIGRAR_TIEMPO') IS NOT NULL
  DROP PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_TIEMPO
GO 

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_MIGRAR_CANAL_VENTA') IS NOT NULL
  DROP PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_CANAL_VENTA
GO 

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_MIGRAR_PROVEEDOR') IS NOT NULL
  DROP PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_PROVEEDOR
GO 

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_MIGRAR_MEDIO_PAGO') IS NOT NULL
  DROP PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_MEDIO_PAGO
GO 

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_MIGRAR_PRODUCTO_VARIANTE') IS NOT NULL
  DROP PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_PRODUCTO_VARIANTE
GO 

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_MIGRAR_PROVINCIA') IS NOT NULL
  DROP PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_PROVINCIA
GO 

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_MIGRAR_RANGO_ETARIO') IS NOT NULL
  DROP PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_RANGO_ETARIO
GO 

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_MIGRAR_TIPO_DESCUENTO') IS NOT NULL
  DROP PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_TIPO_DESCUENTO
GO 

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_MIGRAR_TIPO_ENVIO') IS NOT NULL
  DROP PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_TIPO_ENVIO
GO 

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_MIGRAR_HECHO_VENTA_PRODUCTO') IS NOT NULL
  DROP PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_HECHO_VENTA_PRODUCTO
GO 

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_MIGRAR_HECHO_COMPRA_PRODUCTO') IS NOT NULL
  DROP PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_HECHO_COMPRA_PRODUCTO
GO 

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_MIGRAR_HECHO_DESCUENTO') IS NOT NULL
  DROP PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_HECHO_DESCUENTO
GO 

IF OBJECT_ID('BI_CODIGO_ENIGMA.BI_MIGRAR_PRODUCTO_CATEGORIA') IS NOT NULL
  DROP PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_PRODUCTO_CATEGORIA
GO

--DROPEO DE VISTAS

IF OBJECT_ID('BI_CODIGO_ENIGMA.bi_vista_punto_1', 'V') IS NOT NULL
	DROP VIEW BI_CODIGO_ENIGMA.bi_vista_punto_1
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.bi_vista_punto_2', 'V') IS NOT NULL
	DROP VIEW BI_CODIGO_ENIGMA.bi_vista_punto_2
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.bi_vista_punto_3', 'V') IS NOT NULL
	DROP VIEW BI_CODIGO_ENIGMA.bi_vista_punto_3
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.bi_vista_punto_4', 'V') IS NOT NULL
	DROP VIEW BI_CODIGO_ENIGMA.bi_vista_punto_4
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.bi_vista_punto_5', 'V') IS NOT NULL
	DROP VIEW BI_CODIGO_ENIGMA.bi_vista_punto_5
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.bi_vista_punto_6', 'V') IS NOT NULL
	DROP VIEW BI_CODIGO_ENIGMA.bi_vista_punto_6
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.bi_vista_punto_7', 'V') IS NOT NULL
	DROP VIEW BI_CODIGO_ENIGMA.bi_vista_punto_7
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.bi_vista_punto_8', 'V') IS NOT NULL
	DROP VIEW BI_CODIGO_ENIGMA.bi_vista_punto_8
GO

IF OBJECT_ID('BI_CODIGO_ENIGMA.bi_vista_punto_9', 'V') IS NOT NULL
	DROP VIEW BI_CODIGO_ENIGMA.bi_vista_punto_9
GO

--DROP ESQUEMA
IF EXISTS (SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'BI_CODIGO_ENIGMA')
  DROP SCHEMA BI_CODIGO_ENIGMA
GO

-- CREO ESQUEMA
CREATE SCHEMA BI_CODIGO_ENIGMA
GO

--creacion de tablas de BI

CREATE TABLE BI_CODIGO_ENIGMA.BI_DIM_TIPO_DESCUENTO(
   	TIPO_DESCUENTO_CODIGO INT IDENTITY(1,1) NOT NULL,
   	VENTA_DESCUENTO_CONCEPTO NVARCHAR(50)
);

CREATE TABLE BI_CODIGO_ENIGMA.BI_DIM_TIEMPO (
   	DIM_TIEMPO_CODIGO INT IDENTITY(1,1) NOT NULL,
   	DIM_TIEMPO_ANIO INT,
   	DIM_TIEMPO_MES INT
);

CREATE TABLE BI_CODIGO_ENIGMA.BI_DIM_PROVEEDOR (
   	DIM_PROVEEDOR_CODIGO INT NOT NULL,
   	PROVEEDOR_CUIT NVARCHAR(50),

);

CREATE TABLE BI_CODIGO_ENIGMA.BI_DIM_PRODUCTO_VARIANTE (
   	PRODUCTO_VARIANTE_CODIGO NVARCHAR(50) NOT NULL,
   	PRODUCTO_CODIGO NVARCHAR(50)
);


CREATE TABLE BI_CODIGO_ENIGMA.BI_DIM_PROVINCIA (
   	PROVINCIA_CODIGO INT NOT NULL,
   	PROVINCIA_NOMBRE nvarchar(255) NULL
);

CREATE TABLE BI_CODIGO_ENIGMA.BI_DIM_RANGO_ETARIO_CLIENTE (
   	DIM_RANGO_ETARIO_CODIGO INT IDENTITY(1,1) NOT NULL,
   	DIM_RANGO_ETARIO_INICIAL INT,
	DIM_RANGO_ETARIO_FINAL INT
);

CREATE TABLE BI_CODIGO_ENIGMA.BI_DIM_PRODUCTO_CATEGORIA (
   	PRODUCTO_CATEGORIA_CODIGO INT NOT NULL,
   	PRODUCTO_CATEGORIA nvarchar(255) NULL
);

CREATE TABLE BI_CODIGO_ENIGMA.BI_DIM_CANAL_VENTA (
   	CANAL_VENTA_CODIGO INT NOT NULL,
   	VENTA_CANAL_COSTO DECIMAL(18,2),
	VENTA_CANAL NVARCHAR(255)
);

CREATE TABLE BI_CODIGO_ENIGMA.BI_DIM_MEDIO_PAGO (
   	MEDIO_PAGO_VENTA_CODIGO INT NOT NULL,
	MEDIO_PAGO nvarchar(255),
   	VENTA_MEDIO_PAGO_COSTO decimal(18,2)
);

CREATE TABLE BI_CODIGO_ENIGMA.BI_DIM_TIPO_ENVIO (
   	MEDIO_ENVIO_VENTA_CODIGO INT NOT NULL,
   	VENTA_MEDIO_ENVIO nvarchar(255),
	VENTA_ENVIO_PRECIO decimal(18,2)
);


-- Creacion tabla nuevas BI

CREATE TABLE BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO(
   	HECHO_VENTA_CODIGO INT IDENTITY(1,1) NOT NULL,
   	MEDIO_PAGO_CODIGO INT,
   	PRODUCTO_VARIANTE_CODIGO nvarchar(50),
   	DIM_TIEMPO_CODIGO INT ,
	MEDIO_ENVIO_CODIGO INT,
	DIM_RANGO_ETARIO_CLIENTE INT,
	CANAL_VENTA_CODIGO INT,
	PROVINCIA_CODIGO INT,
	PRODUCTO_CATEGORIA_CODIGO INT,
	CANTIDAD_PRODUCTO decimal(18,0),
	PRECIO_VENTA decimal(18,2),
	COSTO_MEDIO_PAGO decimal(18,2)
)

CREATE TABLE BI_CODIGO_ENIGMA.BI_HECHO_COMPRA_PRODUCTO(
   	HECHO_COMPRA_CODIGO INT IDENTITY(1,1) NOT NULL,
   	PROVEEDOR_CODIGO INT,
	PRODUCTO_VARIANTE_CODIGO nvarchar(50),
	DIM_TIEMPO_CODIGO INT,
	PRECIO_COMPRA decimal(18,2),
	COMPRA_PRODUCTO_CANTIDAD decimal(18,0)
)

CREATE TABLE BI_CODIGO_ENIGMA.BI_HECHO_DESCUENTO(
   	HECHO_DESCUENTO_CODIGO INT IDENTITY(1,1) NOT NULL,
	TIPO_DESCUENTO_CODIGO INT,
	CANAL_VENTA_CODIGO INT,
   	DIM_TIEMPO_CODIGO INT,
	MEDIO_PAGO_CODIGO INT,
	VENTA_DESCUENTO_IMPORTE decimal(18,2)
)


--- ALTER TABLE PRIMARY KEYS

ALTER TABLE BI_CODIGO_ENIGMA.BI_Dim_Tiempo
ADD CONSTRAINT PK_BI_CODIGO_TIEMPO PRIMARY KEY(DIM_TIEMPO_CODIGO)

ALTER TABLE BI_CODIGO_ENIGMA.BI_Dim_Provincia
ADD CONSTRAINT PK_BI_PROVINCIA PRIMARY KEY(PROVINCIA_CODIGO) 

ALTER TABLE BI_CODIGO_ENIGMA.BI_DIM_RANGO_ETARIO_CLIENTE
ADD CONSTRAINT PK_BI_Rango_Etario PRIMARY KEY(DIM_RANGO_ETARIO_CODIGO)
 
ALTER TABLE BI_CODIGO_ENIGMA.BI_Dim_Canal_Venta
ADD CONSTRAINT PK_BI_Canal_Venta PRIMARY KEY(CANAL_VENTA_CODIGO)

ALTER TABLE BI_CODIGO_ENIGMA.BI_Dim_Medio_Pago
ADD CONSTRAINT PK_BI_Medio_Pago PRIMARY KEY(MEDIO_PAGO_VENTA_CODIGO)

ALTER TABLE BI_CODIGO_ENIGMA.BI_Dim_Producto_CATEGORIA
ADD CONSTRAINT PK_BI_Categoria_Producto PRIMARY KEY(PRODUCTO_CATEGORIA_CODIGO)
 
ALTER TABLE BI_CODIGO_ENIGMA.BI_Dim_Producto_variante
ADD CONSTRAINT PK_BI_Producto_variante PRIMARY KEY(PRODUCTO_VARIANTE_CODIGO)

ALTER TABLE BI_CODIGO_ENIGMA.BI_Dim_Tipo_Descuento
ADD CONSTRAINT PK_BI_Tipo_Descuento PRIMARY KEY(TIPO_DESCUENTO_CODIGO)
 
ALTER TABLE BI_CODIGO_ENIGMA.BI_Dim_Tipo_Envio
ADD CONSTRAINT PK_BI_Tipo_Envio PRIMARY KEY(MEDIO_ENVIO_VENTA_CODIGO)

ALTER TABLE BI_CODIGO_ENIGMA.BI_Dim_Proveedor
ADD CONSTRAINT PK_BI_Proveedor PRIMARY KEY(DIM_PROVEEDOR_CODIGO)


-- TABLA DE HECHOS

ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_COMPRA_PRODUCTO
ADD CONSTRAINT PK_BI_HECHO_COMPRA PRIMARY KEY(HECHO_COMPRA_CODIGO)

ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO
ADD CONSTRAINT PK_BI_HECHO_VENTA_PRODUCTO PRIMARY KEY(HECHO_VENTA_CODIGO)

ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_DESCUENTO
ADD CONSTRAINT PK_BI_HECHO_DESCUENTO PRIMARY KEY(HECHO_DESCUENTO_CODIGO)


--- ALTER TABLE FOREIGN KEYS NUEVOS FACTS
 
ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO
   	ADD CONSTRAINT FK_V_MEDIO_PAGO_CODIGO FOREIGN KEY (MEDIO_PAGO_CODIGO) REFERENCES BI_CODIGO_ENIGMA.BI_DIM_MEDIO_PAGO(MEDIO_PAGO_VENTA_CODIGO),
   	CONSTRAINT FK_V_PRODUCTO_VARIANTE_CODIGO FOREIGN KEY(PRODUCTO_VARIANTE_CODIGO) REFERENCES BI_CODIGO_ENIGMA.BI_DIM_PRODUCTO_VARIANTE(PRODUCTO_VARIANTE_CODIGO),
   	CONSTRAINT FK_V_DIM_TIPO_CODIGO FOREIGN KEY (DIM_TIEMPO_CODIGO) REFERENCES BI_CODIGO_ENIGMA.BI_DIM_TIEMPO(DIM_TIEMPO_CODIGO),
   	CONSTRAINT FK_V_MEDIO_ENVIO_CODIGO FOREIGN KEY (MEDIO_ENVIO_CODIGO) REFERENCES BI_CODIGO_ENIGMA.BI_DIM_TIPO_ENVIO(MEDIO_ENVIO_VENTA_CODIGO),
	CONSTRAINT FK_V_DIM_RANGO_ETARIO FOREIGN KEY (DIM_RANGO_ETARIO_CLIENTE) REFERENCES BI_CODIGO_ENIGMA.BI_DIM_RANGO_ETARIO_CLIENTE(DIM_RANGO_ETARIO_CODIGO),
	CONSTRAINT FK_V_CANAL_VENTA_CODIGO FOREIGN KEY (CANAL_VENTA_CODIGO) REFERENCES BI_CODIGO_ENIGMA.BI_DIM_CANAL_VENTA(CANAL_VENTA_CODIGO),
	CONSTRAINT FK_V_DIM_PROVINCIA FOREIGN KEY (PROVINCIA_CODIGO) REFERENCES BI_CODIGO_ENIGMA.BI_DIM_PROVINCIA(PROVINCIA_CODIGO),
	CONSTRAINT FK_V_DIM_PRODUCTO_CATEGORIA FOREIGN KEY (PRODUCTO_CATEGORIA_CODIGO) REFERENCES BI_CODIGO_ENIGMA.BI_DIM_PRODUCTO_CATEGORIA(PRODUCTO_CATEGORIA_CODIGO)

ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_COMPRA_PRODUCTO
   	ADD CONSTRAINT FK_C_DIM_TIEMPO_CODIGO FOREIGN KEY (DIM_TIEMPO_CODIGO) REFERENCES BI_CODIGO_ENIGMA.BI_DIM_TIEMPO(DIM_TIEMPO_CODIGO),
   	CONSTRAINT FK_C_PROVEEDOR_CODIGO FOREIGN KEY(PROVEEDOR_CODIGO) REFERENCES BI_CODIGO_ENIGMA.BI_DIM_PROVEEDOR(DIM_PROVEEDOR_CODIGO),
	CONSTRAINT FK_C_PRODUCTO_VARIANTE_CODIGO FOREIGN KEY(PRODUCTO_VARIANTE_CODIGO) REFERENCES BI_CODIGO_ENIGMA.BI_DIM_PRODUCTO_VARIANTE(PRODUCTO_VARIANTE_CODIGO)
	


 ALTER TABLE BI_CODIGO_ENIGMA.BI_HECHO_DESCUENTO
	ADD CONSTRAINT FK_D_TIPO_DESCUENTO_CODIGO FOREIGN KEY (TIPO_DESCUENTO_CODIGO) REFERENCES BI_CODIGO_ENIGMA.BI_DIM_TIPO_DESCUENTO(TIPO_DESCUENTO_CODIGO),
		CONSTRAINT FK_D_DIM_TIEMPO_CODIGO FOREIGN KEY (DIM_TIEMPO_CODIGO) REFERENCES BI_CODIGO_ENIGMA.BI_DIM_TIEMPO(DIM_TIEMPO_CODIGO),
		CONSTRAINT FK_D_DIM_CANAL_VENTA_CODIGO FOREIGN KEY (CANAL_VENTA_CODIGO) REFERENCES BI_CODIGO_ENIGMA.BI_DIM_CANAL_VENTA(CANAL_VENTA_CODIGO),
		CONSTRAINT FK_D_DIM_MEDIO_PAGO_CODIGO FOREIGN KEY (MEDIO_PAGO_CODIGO) REFERENCES BI_CODIGO_ENIGMA.BI_DIM_MEDIO_PAGO(MEDIO_PAGO_VENTA_CODIGO)
GO
 

 -- creacion de funciones

 CREATE FUNCTION BI_CODIGO_ENIGMA.OBTENER_RANGO_ETARIO(@FECHA_NAC datetime)
RETURNS int
BEGIN

	declare @EDAD int
	SET @EDAD = ( YEAR(GETDATE()) - YEAR(@FECHA_NAC))


	IF( MONTH(GETDATE()) <  MONTH(@FECHA_NAC))
	BEGIN
			SET @EDAD = @EDAD - 1 
	END
	IF( MONTH(GETDATE()) =  MONTH(@FECHA_NAC))
	BEGIN
			IF( DAY(GETDATE()) <  DAY(@FECHA_NAC))
			BEGIN
				 SET @EDAD = @EDAD - 1
			END
	END


  	RETURN (
   		   CASE
		   WHEN @EDAD < 25 THEN 1
		   WHEN @EDAD >= 25 and @EDAD < 35 THEN 2
   		   WHEN @EDAD >= 35 AND @EDAD <= 55 THEN 3
   		   ELSE 4
   		   END )
END
GO

 CREATE FUNCTION BI_CODIGO_ENIGMA.OBTENER_DIM_TIEMPO_CODIGO(@anio int, @mes int)
RETURNS INT
AS
BEGIN 
  DECLARE @CODIGO as int
  SELECT DISTINCT @CODIGO = dim_tiempo_codigo FROM BI_CODIGO_ENIGMA.BI_Dim_Tiempo
  WHERE @anio = DIM_TIEMPO_ANIO and @mes = DIM_TIEMPO_MES
  RETURN @codigo
END 
GO 


 CREATE FUNCTION BI_CODIGO_ENIGMA.OBTENER_TIPO_DESCUENTO_CODIGO(@TIPO_DESCUENTO_CODIGO NVARCHAR(255))
RETURNS INT
AS
BEGIN 
  DECLARE @CODIGO as int
  
  SET @CODIGO = 5

  IF(@TIPO_DESCUENTO_CODIGO = 'Efectivo')
	SET @CODIGO = 1
  IF(@TIPO_DESCUENTO_CODIGO= 'Transferencia')
	SET @CODIGO = 4
  IF(@TIPO_DESCUENTO_CODIGO = 'Otros')--se hace diferencia aca entre ENVIO GRATIS y DESCUENTO ESPECIAL, pero como en el sistema no tenemos casos o formas de saber cuando se 
	SET @CODIGO = 2
  IF(@TIPO_DESCUENTO_CODIGO ='')
	SET @CODIGO = 3
  
	
  return @CODIGO
END 
GO  


 
 --Migracion de las tablas

--Migrar tiempo
CREATE PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_TIEMPO
AS
BEGIN
INSERT INTO BI_CODIGO_ENIGMA.BI_Dim_Tiempo (DIM_TIEMPO_ANIO, DIM_TIEMPO_MES)
   		    (select distinct year(VENTA_FECHA) ,month(venta_FECHA)
   		    from CODIGO_ENIGMA.VENTA
   		    where VENTA_FECHA is not null)
			UNION
			(select distinct year(COMPRA_FECHA) ,month(COMPRA_FECHA)
   		    from CODIGO_ENIGMA.COMPRA
   		    where COMPRA_FECHA is not null)
END
GO
 
--Migrar Tipo Descuento 
CREATE PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_TIPO_DESCUENTO
AS
BEGIN
	INSERT INTO BI_CODIGO_ENIGMA.BI_DIM_TIPO_DESCUENTO(VENTA_DESCUENTO_CONCEPTO)
	VALUES('EFECTIVO'),
		  ('DESCUENTO ESPECIAL'),
		  ('CUPON'),
		  ('TRANSFERENCIA') 
END
GO


--Migrar Proveedor
CREATE PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_PROVEEDOR
AS
BEGIN
	INSERT INTO BI_CODIGO_ENIGMA.BI_DIM_PROVEEDOR(DIM_PROVEEDOR_CODIGO, PROVEEDOR_CUIT)
	SELECT PROVEEDOR_CODIGO, PROVEEDOR_CUIT
	FROM CODIGO_ENIGMA.PROVEEDOR
END
GO

--Migrar Producto Variante
CREATE PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_PRODUCTO_VARIANTE
AS
BEGIN
	INSERT INTO BI_CODIGO_ENIGMA.BI_DIM_PRODUCTO_VARIANTE(PRODUCTO_VARIANTE_CODIGO, PRODUCTO_CODIGO)
	SELECT DISTINCT PRODUCTO_VARIANTE_ID, PRODUCTO_CODIGO
	FROM CODIGO_ENIGMA.PRODUCTO_VARIANTE
END
GO

--Migrar Categoria
CREATE PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_PRODUCTO_CATEGORIA
AS
BEGIN
	INSERT INTO BI_CODIGO_ENIGMA.BI_DIM_PRODUCTO_CATEGORIA(PRODUCTO_CATEGORIA_CODIGO, PRODUCTO_CATEGORIA)
	SELECT PRODUCTO_CATEGORIA_CODIGO, PRODUCTO_CATEGORIA
	FROM CODIGO_ENIGMA.PRODUCTO_CATEGORIA
END
GO

--Migrar provincias
CREATE PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_PROVINCIA
AS
BEGIN
	INSERT INTO BI_CODIGO_ENIGMA.BI_DIM_PROVINCIA(PROVINCIA_CODIGO, PROVINCIA_NOMBRE)
	SELECT PROVINCIA_CODIGO, PROVINCIA_NOMBRE
	FROM CODIGO_ENIGMA.PROVINCIA
END
GO


--Migrar rango etario
CREATE PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_RANGO_ETARIO
 AS
  BEGIN
 INSERT INTO BI_CODIGO_ENIGMA.BI_DIM_RANGO_ETARIO_CLIENTE(DIM_RANGO_ETARIO_INICIAL, DIM_RANGO_ETARIO_FINAL)
   		VALUES 	(0,25),
       			(25,35),
				(35,55),
				(56,200)
END
GO

--Migrar Canal Ventas
CREATE PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_CANAL_VENTA
AS
BEGIN
	INSERT INTO BI_CODIGO_ENIGMA.BI_DIM_CANAL_VENTA(CANAL_VENTA_CODIGO, VENTA_CANAL_COSTO, VENTA_CANAL)
	SELECT CANAL_VENTA_CODIGO, VENTA_CANAL_COSTO, VENTA_CANAL
	FROM CODIGO_ENIGMA.CANAL_VENTA CV JOIN CODIGO_ENIGMA.CANAL C ON CV.CANAL_CODIGO = C.CANAL_CODIGO
END
GO

--Migrar Medio Pago
CREATE PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_MEDIO_PAGO
AS
BEGIN
	INSERT INTO BI_CODIGO_ENIGMA.BI_DIM_MEDIO_PAGO(MEDIO_PAGO_VENTA_CODIGO, MEDIO_PAGO, VENTA_MEDIO_PAGO_COSTO)
	SELECT MEDIO_PAGO_VENTA_CODIGO, MEDIO_PAGO, VENTA_MEDIO_PAGO_COSTO
	FROM CODIGO_ENIGMA.MEDIO_PAGO_VENTA MPV
	JOIN CODIGO_ENIGMA.MEDIO_PAGO MP on MPV.MEDIO_PAGO_CODIGO = MP.MEDIO_PAGO_CODIGO
END
GO



--Migrar Tipo Envio
CREATE PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_TIPO_ENVIO
AS
BEGIN
	INSERT INTO BI_CODIGO_ENIGMA.BI_DIM_TIPO_ENVIO(MEDIO_ENVIO_VENTA_CODIGO, VENTA_MEDIO_ENVIO, VENTA_ENVIO_PRECIO)
	SELECT MEV.MEDIO_ENVIO_VENTA_CODIGO, ME.VENTA_MEDIO_ENVIO, MEV.VENTA_ENVIO_PRECIO
	FROM CODIGO_ENIGMA.MEDIO_ENVIO_VENTA MEV JOIN CODIGO_ENIGMA.MEDIO_ENVIO ME ON MEV.MEDIO_ENVIO_CODIGO = ME.MEDIO_ENVIO_CODIGO
END
GO

--Migracion de hechos
CREATE PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_HECHO_COMPRA_PRODUCTO
AS
BEGIN
INSERT INTO BI_CODIGO_ENIGMA.BI_HECHO_COMPRA_PRODUCTO(PROVEEDOR_CODIGO, PRODUCTO_VARIANTE_CODIGO, DIM_TIEMPO_CODIGO, PRECIO_COMPRA, COMPRA_PRODUCTO_CANTIDAD)
	SELECT  C.PROVEEDOR_CODIGO,
			PV.PRODUCTO_VARIANTE_ID,
			BI_CODIGO_ENIGMA.OBTENER_DIM_TIEMPO_CODIGO(YEAR(C.COMPRA_FECHA), MONTH(C.COMPRA_FECHA)),
			PV.PRODUCTO_VARIANTE_PRECIO,
			SUM(CP.COMPRA_PRODUCTO_CANTIDAD)
	FROM CODIGO_ENIGMA.COMPRAxPRODUCTO CP
	JOIN CODIGO_ENIGMA.COMPRA C ON CP.COMPRA_NUMERO = C.COMPRA_NUMERO
	JOIN CODIGO_ENIGMA.PRODUCTO_VARIANTE PV on CP.PRODUCTO_VARIANTE_CODIGO = PV.PRODUCTO_VARIANTE_CODIGO
	GROUP BY C.PROVEEDOR_CODIGO, PV.PRODUCTO_VARIANTE_ID, BI_CODIGO_ENIGMA.OBTENER_DIM_TIEMPO_CODIGO(YEAR(C.COMPRA_FECHA), MONTH(C.COMPRA_FECHA)), PV.PRODUCTO_VARIANTE_PRECIO
END
GO


CREATE PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_HECHO_VENTA_PRODUCTO
AS
BEGIN
INSERT INTO BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO(MEDIO_PAGO_CODIGO, PRODUCTO_VARIANTE_CODIGO, DIM_TIEMPO_CODIGO, MEDIO_ENVIO_CODIGO, DIM_RANGO_ETARIO_CLIENTE, CANAL_VENTA_CODIGO, PROVINCIA_CODIGO, PRODUCTO_CATEGORIA_CODIGO, CANTIDAD_PRODUCTO, PRECIO_VENTA, COSTO_MEDIO_PAGO)
		SELECT VENTA.MEDIO_PAGO_VENTA_CODIGO,
			PV.PRODUCTO_VARIANTE_ID,
			BI_CODIGO_ENIGMA.OBTENER_DIM_TIEMPO_CODIGO(year(VENTA.VENTA_FECHA), month(VENTA.VENTA_FECHA)),
			VENTA.MEDIO_ENVIO_VENTA_CODIGO,
			BI_CODIGO_ENIGMA.OBTENER_RANGO_ETARIO(C.CLIENTE_FECHA_NAC),
			VENTA.CANAL_VENTA_CODIGO,
			L.PROVINCIA_CODIGO,
			P.PRODUCTO_CATEGORIA_CODIGO,
			sum(VXP.VENTA_PRODUCTO_CANTIDAD),
			PV.PRODUCTO_VARIANTE_precio,
			( SELECT SUM(MP.VENTA_MEDIO_PAGO_COSTO) 
				 FROM CODIGO_ENIGMA.VENTA V1
			JOIN CODIGO_ENIGMA.MEDIO_PAGO_VENTA MP ON V1.MEDIO_PAGO_VENTA_CODIGO = MP.MEDIO_PAGO_VENTA_CODIGO
			JOIN CODIGO_ENIGMA.MEDIO_PAGO MP1 ON MP1.MEDIO_PAGO_CODIGO = MP.MEDIO_PAGO_CODIGO
			where BI_CODIGO_ENIGMA.OBTENER_DIM_TIEMPO_CODIGO(year(VENTA.VENTA_FECHA), month(VENTA.VENTA_FECHA)) 
			= BI_CODIGO_ENIGMA.OBTENER_DIM_TIEMPO_CODIGO(year(V1.VENTA_FECHA), month(V1.VENTA_FECHA)) 
			and v1.MEDIO_PAGO_VENTA_CODIGO = venta.MEDIO_PAGO_VENTA_CODIGO
			and v1.CANAL_VENTA_CODIGO = VENTA.CANAL_VENTA_CODIGO
			 GROUP BY   BI_CODIGO_ENIGMA.OBTENER_DIM_TIEMPO_CODIGO(year(V1.VENTA_FECHA), month(V1.VENTA_FECHA)) ,  v1.MEDIO_PAGO_VENTA_CODIGO, v1.CANAL_VENTA_CODIGO) -- costo medio de pago por medio de pago
         	from CODIGO_ENIGMA.VENTA as VENTA
			join CODIGO_ENIGMA.VENTAxPRODUCTO VXP on venta.VENTA_CODIGO = vxp.VENTA_CODIGO
			join CODIGO_ENIGMA.CLIENTE C on c.CLIENTE_CODIGO = venta.CLIENTE_CODIGO 
			join CODIGO_ENIGMA.PRODUCTO_VARIANTE PV on vxp.PRODUCTO_VARIANTE_CODIGO = pv.PRODUCTO_VARIANTE_CODIGO
			join CODIGO_ENIGMA.MEDIO_ENVIO_VENTA MV on MV.MEDIO_ENVIO_VENTA_CODIGO = VENTA.MEDIO_ENVIO_VENTA_CODIGO
			join CODIGO_ENIGMA.LOCALIDAD L on L.LOCALIDAD_CODIGO = MV.LOCALIDAD_CODIGO
			join CODIGO_ENIGMA.PRODUCTO P on P.PRODUCTO_CODIGO = PV.PRODUCTO_CODIGO
			group by VENTA.MEDIO_PAGO_VENTA_CODIGO,
			VENTA.VENTA_CODIGO,
			PV.PRODUCTO_VARIANTE_ID,
			BI_CODIGO_ENIGMA.OBTENER_DIM_TIEMPO_CODIGO(year(VENTA.VENTA_FECHA), month(VENTA.VENTA_FECHA)),
			VENTA.MEDIO_ENVIO_VENTA_CODIGO,
			BI_CODIGO_ENIGMA.OBTENER_RANGO_ETARIO(C.CLIENTE_FECHA_NAC),
			VENTA.CANAL_VENTA_CODIGO,
			L.PROVINCIA_CODIGO,
			P.PRODUCTO_CATEGORIA_CODIGO,
			PV.PRODUCTO_VARIANTE_precio
END
GO


CREATE PROCEDURE BI_CODIGO_ENIGMA.BI_MIGRAR_HECHO_DESCUENTO
AS
BEGIN
INSERT INTO BI_CODIGO_ENIGMA.BI_HECHO_DESCUENTO(TIPO_DESCUENTO_CODIGO, CANAL_VENTA_CODIGO, DIM_TIEMPO_CODIGO, VENTA_DESCUENTO_IMPORTE, MEDIO_PAGO_CODIGO)
   			(select  BI_CODIGO_ENIGMA.OBTENER_TIPO_DESCUENTO_CODIGO(td.VENTA_DESCUENTO_CONCEPTO),
			venta.canal_venta_codigo,
			BI_CODIGO_ENIGMA.OBTENER_DIM_TIEMPO_CODIGO(year(VENTA.VENTA_FECHA), month(VENTA.VENTA_FECHA)),
			sum(dv.venta_descuento_importe),
			VENTA.MEDIO_PAGO_VENTA_CODIGO
         	from CODIGO_ENIGMA.venta as venta
			join CODIGO_ENIGMA.DESCUENTO_VENTA dv on Venta.VENTA_CODIGO = dv.VENTA_CODIGO
			join CODIGO_ENIGMA.TIPO_DESCUENTO td on td.tipo_descuento_codigo = dv.TIPO_DESCUENTO_CODIGO 
			group by td.VENTA_DESCUENTO_CONCEPTO, venta.canal_venta_codigo, BI_CODIGO_ENIGMA.OBTENER_DIM_TIEMPO_CODIGO(year(VENTA.VENTA_FECHA), month(VENTA.VENTA_FECHA)),VENTA.MEDIO_PAGO_VENTA_CODIGO)
			UNION
			(select BI_CODIGO_ENIGMA.OBTENER_TIPO_DESCUENTO_CODIGO(''),
			V.CANAL_VENTA_CODIGO,
			BI_CODIGO_ENIGMA.OBTENER_DIM_TIEMPO_CODIGO(year(V.VENTA_FECHA), month(V.VENTA_FECHA)),
			sum(CXV.VENTA_CUPON_IMPORTE),
			V.MEDIO_PAGO_VENTA_CODIGO
			FROM CODIGO_ENIGMA.VENTA V
			JOIN CODIGO_ENIGMA.CUPONxVENTA CXV on CXV.VENTA_CODIGO = V.VENTA_CODIGO
			group by
			V.CANAL_VENTA_CODIGO,
			BI_CODIGO_ENIGMA.OBTENER_DIM_TIEMPO_CODIGO(year(V.VENTA_FECHA), month(V.VENTA_FECHA)),
			V.MEDIO_PAGO_VENTA_CODIGO)
END
GO

----------- EJECUTAR PROCEDURES
BEGIN TRANSACTION

EXECUTE BI_CODIGO_ENIGMA.BI_migrar_canal_venta
EXECUTE BI_CODIGO_ENIGMA.BI_migrar_tiempo
EXECUTE BI_CODIGO_ENIGMA.BI_MIGRAR_PROVEEDOR
EXECUTE BI_CODIGO_ENIGMA.BI_migrar_medio_pago
EXECUTE BI_CODIGO_ENIGMA.BI_migrar_producto_variante
EXECUTE BI_CODIGO_ENIGMA.BI_migrar_provincia
EXECUTE BI_CODIGO_ENIGMA.BI_migrar_rango_etario
EXECUTE BI_CODIGO_ENIGMA.BI_migrar_tipo_descuento
EXECUTE BI_CODIGO_ENIGMA.BI_migrar_tipo_envio
EXECUTE BI_CODIGO_ENIGMA.BI_MIGRAR_PRODUCTO_CATEGORIA
EXECUTE BI_CODIGO_ENIGMA.BI_MIGRAR_HECHO_VENTA_PRODUCTO
EXECUTE BI_CODIGO_ENIGMA.BI_MIGRAR_HECHO_COMPRA_PRODUCTO
EXECUTE BI_CODIGO_ENIGMA.BI_MIGRAR_HECHO_DESCUENTO

COMMIT TRANSACTION
GO

-- Tarda 3 segundos la migracion

-- Punto 1
/*Las ganancias mensuales de cada canal de venta.
Se entiende por ganancias al total de las ventas, menos el total de las
compras, menos los costos de transacción totales aplicados asociados los
medios de pagos utilizados en las mismas.*/


CREATE VIEW BI_CODIGO_ENIGMA.bi_vista_punto_1
AS
   	SELECT CV.VENTA_CANAL, T.DIM_TIEMPO_ANIO AS AÑO, T.DIM_TIEMPO_MES AS MES, 
	sum(HV.CANTIDAD_PRODUCTO* HV.PRECIO_VENTA) -- ventas por mes
	/*-
	(SELECT ISNULL(SUM(HC1.COMPRA_PRODUCTO_CANTIDAD * HC1.PRECIO_COMPRA),0) 
	 FROM BI_CODIGO_ENIGMA.BI_HECHO_COMPRA_PRODUCTO HC1
	 WHERE HC1.DIM_TIEMPO_CODIGO = HV.DIM_TIEMPO_CODIGO) -- compras del mes
	-
	
	(HV.COSTO_MEDIO_PAGO) -- costo medio pago
	*/
	as GANANCIAS

	FROM BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO HV 
	JOIN BI_CODIGO_ENIGMA.BI_DIM_CANAL_VENTA CV on CV.CANAL_VENTA_CODIGO = HV.CANAL_VENTA_CODIGO
	JOIN BI_CODIGO_ENIGMA.BI_DIM_TIEMPO T ON T.DIM_TIEMPO_CODIGO = HV.DIM_TIEMPO_CODIGO
	JOIN BI_CODIGO_ENIGMA.BI_DIM_MEDIO_PAGO MP ON MP.MEDIO_PAGO_VENTA_CODIGO = HV.MEDIO_PAGO_CODIGO
	GROUP BY CV.VENTA_CANAL, T.DIM_TIEMPO_ANIO, T.DIM_TIEMPO_MES, HV.DIM_TIEMPO_CODIGO, HV.COSTO_MEDIO_PAGO, hv.MEDIO_PAGO_CODIGO
GO

-- Punto 2 
/*Los 5 productos con mayor rentabilidad anual, con sus respectivos %
Se entiende por rentabilidad a los ingresos generados por el producto
(ventas) durante el periodo menos la inversión realizada en el producto
(compras) durante el periodo, todo esto sobre dichos ingresos.
Valor expresado en porcentaje.
Para simplificar, no es necesario tener en cuenta los descuentos aplicados.*/



CREATE VIEW BI_CODIGO_ENIGMA.bi_vista_punto_2
AS
   	SELECT A.DIM_TIEMPO_ANIO AS AÑO, A.PRODUCTO_VARIANTE_CODIGO AS PRODUCTO, A.RENTABILIDAD
	FROM (SELECT ROW_NUMBER() OVER (PARTITION BY TV.DIM_TIEMPO_ANIO ORDER BY (SUM(VP.CANTIDAD_PRODUCTO*VP.PRECIO_VENTA)
																			  - (SELECT TOP 1 ISNULL(SUM(C.PRECIO_COMPRA * C.COMPRA_PRODUCTO_CANTIDAD),0)
																					FROM BI_CODIGO_ENIGMA.BI_HECHO_COMPRA_PRODUCTO C JOIN BI_CODIGO_ENIGMA.BI_DIM_TIEMPO T ON T.DIM_TIEMPO_CODIGO = C.DIM_TIEMPO_CODIGO
																					WHERE C.PRODUCTO_VARIANTE_CODIGO = VP.PRODUCTO_VARIANTE_CODIGO AND T.DIM_TIEMPO_ANIO = TV.DIM_TIEMPO_ANIO
																					GROUP BY C.PRODUCTO_VARIANTE_CODIGO, T.DIM_TIEMPO_ANIO))
																			/SUM(VP.CANTIDAD_PRODUCTO*VP.PRECIO_VENTA) DESC ) R,
			TV.DIM_TIEMPO_ANIO,
			VP.PRODUCTO_VARIANTE_CODIGO,
			concat(((SUM(VP.CANTIDAD_PRODUCTO*VP.PRECIO_VENTA)
				- (SELECT TOP 1 ISNULL(SUM(C.PRECIO_COMPRA * C.COMPRA_PRODUCTO_CANTIDAD),0)
					FROM BI_CODIGO_ENIGMA.BI_HECHO_COMPRA_PRODUCTO C JOIN BI_CODIGO_ENIGMA.BI_DIM_TIEMPO T ON T.DIM_TIEMPO_CODIGO = C.DIM_TIEMPO_CODIGO
					WHERE C.PRODUCTO_VARIANTE_CODIGO = VP.PRODUCTO_VARIANTE_CODIGO AND T.DIM_TIEMPO_ANIO = TV.DIM_TIEMPO_ANIO
					GROUP BY C.PRODUCTO_VARIANTE_CODIGO, T.DIM_TIEMPO_ANIO))
			/SUM(VP.CANTIDAD_PRODUCTO*VP.PRECIO_VENTA)* 100 ),'%') as RENTABILIDAD
			FROM BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO VP
			JOIN BI_CODIGO_ENIGMA.BI_DIM_TIEMPO TV ON TV.DIM_TIEMPO_CODIGO = VP.DIM_TIEMPO_CODIGO
			GROUP BY TV.DIM_TIEMPO_ANIO, VP.PRODUCTO_VARIANTE_CODIGO) A
	WHERE R>0 AND R <= 5
GO


-- Punto 3 
/*Las 5 categorías de productos más vendidos por rango etario de clientes 
por mes.*/


CREATE VIEW BI_CODIGO_ENIGMA.bi_vista_punto_3
AS
   	SELECT A.DIM_TIEMPO_ANIO AS AÑO, A.DIM_TIEMPO_MES AS MES, A.DIM_RANGO_ETARIO_CLIENTE AS RANGO_ETARIO, A.R AS POS, A.PRODUCTO_CATEGORIA, A.PROD_VENDIDOS
	FROM (SELECT ROW_NUMBER() OVER (PARTITION BY TV.DIM_TIEMPO_MES, VP.DIM_RANGO_ETARIO_CLIENTE ORDER BY SUM(VP.CANTIDAD_PRODUCTO) DESC ) R,
			TV.DIM_TIEMPO_ANIO,
			TV.DIM_TIEMPO_MES,
			VP.DIM_RANGO_ETARIO_CLIENTE,
			PC.PRODUCTO_CATEGORIA,
			SUM(VP.CANTIDAD_PRODUCTO) as PROD_VENDIDOS
			FROM BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO VP
			JOIN BI_CODIGO_ENIGMA.BI_DIM_TIEMPO TV ON TV.DIM_TIEMPO_CODIGO = VP.DIM_TIEMPO_CODIGO
			JOIN BI_CODIGO_ENIGMA.BI_DIM_PRODUCTO_CATEGORIA PC ON PC.PRODUCTO_CATEGORIA_CODIGO = VP.PRODUCTO_CATEGORIA_CODIGO
			GROUP BY TV.DIM_TIEMPO_ANIO, TV.DIM_TIEMPO_MES, VP.DIM_RANGO_ETARIO_CLIENTE, PC.PRODUCTO_CATEGORIA) A
	WHERE R>0 AND R <= 5
GO

-- Punto 4 
/*Total de Ingresos por cada medio de pago por mes, descontando los costos
por medio de pago (en caso que aplique) y descuentos por medio de pago
(en caso que aplique)*/

create view BI_codigo_enigma.bi_vista_punto_4
as
	select
		T.DIM_TIEMPO_ANIO AS AÑO,
		T.DIM_TIEMPO_MES AS MES,
		mp.MEDIO_PAGO,
		sum(hv.CANTIDAD_PRODUCTO * HV.precio_venta) -- ingresos
		- 
		(SELECT top 1 SUM(DISTINCT HV2.COSTO_MEDIO_PAGO) -- costo medio pago
		FROM BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO HV2 
		JOIN BI_CODIGO_ENIGMA.BI_DIM_CANAL_VENTA CV2 on CV2.CANAL_VENTA_CODIGO = HV2.CANAL_VENTA_CODIGO
		JOIN BI_CODIGO_ENIGMA.BI_DIM_TIEMPO T2 ON T2.DIM_TIEMPO_CODIGO = HV2.DIM_TIEMPO_CODIGO
		JOIN BI_CODIGO_ENIGMA.BI_DIM_MEDIO_PAGO MP2 ON MP2.MEDIO_PAGO_VENTA_CODIGO = HV2.MEDIO_PAGO_CODIGO
		where mp2.MEDIO_PAGO = mp.MEDIO_PAGO and t2.DIM_TIEMPO_CODIGO = t.DIM_TIEMPO_CODIGO
		GROUP BY CV2.VENTA_CANAL, hv2.MEDIO_PAGO_CODIGO, t2.DIM_TIEMPO_CODIGO
		)
		- isnull((select sum(HD1.venta_descuento_importe) from BI_CODIGO_ENIGMA.BI_HECHO_DESCUENTO HD1 
		join BI_CODIGO_ENIGMA.BI_Dim_Tiempo T1 ON HD1.dim_tiempo_codigo = T1.dim_tiempo_codigo
		where T.DIM_TIEMPO_ANIO =  T1.DIM_TIEMPO_ANIO and T1.DIM_TIEMPO_MES = T.DIM_TIEMPO_MES
		AND hd1.TIPO_DESCUENTO_CODIGO = hd1.MEDIO_PAGO_CODIGO
		and HD1.MEDIO_PAGO_CODIGO = HV.medio_pago_codigo),0) as 'importe total'   -- el tercer termino todavia no lo revise bien
	from BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO HV join BI_CODIGO_ENIGMA.BI_Dim_Medio_Pago MP on HV.medio_pago_codigo = MP.MEDIO_PAGO_VENTA_CODIGO
	join BI_CODIGO_ENIGMA.BI_Dim_Tiempo T on HV.dim_tiempo_codigo = T.dim_tiempo_codigo
	group by HV.medio_pago_codigo,T.DIM_TIEMPO_ANIO,T.DIM_TIEMPO_MES, mp.MEDIO_PAGO, t.DIM_TIEMPO_CODIGO
go


-- Punto 5 
/*Importe total en descuentos aplicados según su tipo de descuento, por
canal de venta, por mes. Se entiende por tipo de descuento como los
correspondientes a envío, medio de pago, cupones, etc)*/


create view BI_codigo_enigma.bi_vista_punto_5
as
	select 
		sum(venta_descuento_importe) as 'Total Aplicado',
		tipoDesc.VENTA_DESCUENTO_CONCEPTO,
		cv.venta_canal,
		t.DIM_TIEMPO_ANIO AS ANIO,
		t.dim_tiempo_mes AS MES
	from BI_CODIGO_ENIGMA.BI_HECHO_DESCUENTO d join BI_CODIGO_ENIGMA.BI_Dim_Tipo_Descuento tipoDesc on tipoDesc.tipo_descuento_codigo = d.tipo_descuento_codigo
	join BI_CODIGO_ENIGMA.BI_Dim_Tiempo t on t.dim_tiempo_codigo = d.dim_tiempo_codigo
	join BI_CODIGO_ENIGMA.BI_Dim_Canal_Venta cv on cv.canal_venta_codigo = d.canal_venta_codigo
	group by tipoDesc.VENTA_DESCUENTO_CONCEPTO, cv.venta_canal, t.dim_tiempo_mes, t.DIM_TIEMPO_ANIO
go


-- Punto 6 
/*Porcentaje de envíos realizados a cada Provincia por mes. El porcentaje
debe representar la cantidad de envíos realizados a cada provincia sobre
total de envío mensuales.*/

create view BI_codigo_enigma.bi_vista_punto_6
as

	select
		P.provincia_nombre as PROVINCIA,
		T.DIM_TIEMPO_ANIO AS ANIO,
		t.DIM_TIEMPO_MES AS MES,
		concat((count(e.MEDIO_ENVIO_VENTA_CODIGO)*100)/ 
				(select count(e1.MEDIO_ENVIO_VENTA_CODIGO) from BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO HV1 join BI_CODIGO_ENIGMA.BI_Dim_Tipo_Envio e1 on HV1.medio_envio_codigo = E1.MEDIO_ENVIO_VENTA_CODIGO
				join BI_CODIGO_ENIGMA.BI_Dim_Tiempo T1 on T1.dim_tiempo_codigo = HV1.dim_tiempo_codigo
				where t1.dim_tiempo_codigo = t.dim_tiempo_codigo
				and e1.VENTA_MEDIO_ENVIO != 'Entrega en sucursal'), '%') as 'porcentaje de envios' 
	from BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO HV join BI_CODIGO_ENIGMA.BI_Dim_Tipo_Envio e on HV.medio_envio_codigo = e.MEDIO_ENVIO_VENTA_CODIGO
	join BI_CODIGO_ENIGMA.BI_Dim_Provincia p on HV.provincia_codigo = P.provincia_codigo
	join BI_CODIGO_ENIGMA.BI_Dim_Tiempo T on T.dim_tiempo_codigo = HV.dim_tiempo_codigo
	where e.VENTA_MEDIO_ENVIO != 'Entrega en sucursal'
	group by P.provincia_nombre, P.provincia_codigo , T.DIM_TIEMPO_ANIO, t.DIM_TIEMPO_MES, T.DIM_TIEMPO_CODIGO

go



-- Punto 7 
/*Valor promedio de envío por Provincia por Medio De Envío anual.
*/

CREATE VIEW BI_CODIGO_ENIGMA.bi_vista_punto_7 
AS
   	SELECT 
	T.dim_tiempo_anio AS AÑO,
	P.provincia_nombre AS PROVINCIA,
	E.venta_medio_envio AS MEDIO_ENVIO,
	avg(E.venta_envio_precio) as 'promedio de envio'
   	FROM BI_CODIGO_ENIGMA.BI_HECHO_VENTA_PRODUCTO HV 
	join BI_CODIGO_ENIGMA.BI_Dim_Tipo_Envio E on HV.medio_envio_codigo = E.MEDIO_ENVIO_VENTA_CODIGO
	join BI_CODIGO_ENIGMA.BI_Dim_Provincia P on P.provincia_codigo = HV.PROVINCIA_CODIGO
	join BI_CODIGO_ENIGMA.BI_Dim_Tiempo T on T.dim_tiempo_codigo = HV.dim_tiempo_codigo
	group by P.provincia_nombre, E.venta_medio_envio, T.dim_tiempo_anio
GO
 

-- Punto 8  
/*Aumento promedio de precios de cada proveedor anual. Para calcular este
indicador se debe tomar como referencia el máximo precio por año menos
el mínimo todo esto divido el mínimo precio del año. Teniendo en cuenta
que los precios siempre van en aumento.*/

CREATE VIEW BI_CODIGO_ENIGMA.BI_VISTA_punto_8 
AS
   	SELECT  
		hc.proveedor_codigo AS PROVEEDOR,
		p.PROVEEDOR_CUIT,
		(select CONCAT(avg(promedio) * 100, '%') from(select (max(hc1.precio_compra) - min(hc1.precio_compra)) / min(hc1.precio_compra) as promedio
		 from BI_CODIGO_ENIGMA.BI_HECHO_COMPRA_PRODUCTO HC1 
		join BI_CODIGO_ENIGMA.BI_Dim_Tiempo t1 on t1.dim_tiempo_codigo = hc1.dim_tiempo_codigo
		join BI_CODIGO_ENIGMA.BI_Dim_Proveedor p1 on p1.dim_proveedor_codigo = hc1.proveedor_codigo
		WHERE HC.PROVEEDOR_CODIGO = HC1.PROVEEDOR_CODIGO and t.DIM_TIEMPO_ANIO = t1.DIM_TIEMPO_ANIO
		group by hc1.PRODUCTO_VARIANTE_CODIGO) as t) as 'aumento promedio', 
		T.DIM_TIEMPO_ANIO AS AÑO
		FROM BI_CODIGO_ENIGMA.BI_HECHO_COMPRA_PRODUCTO HC
		join BI_CODIGO_ENIGMA.BI_Dim_Proveedor p on p.dim_proveedor_codigo = hc.proveedor_codigo
		join BI_CODIGO_ENIGMA.BI_Dim_Tiempo t on t.dim_tiempo_codigo = hc.dim_tiempo_codigo
		group by hc.proveedor_codigo,p.PROVEEDOR_CUIT, t.dim_tiempo_anio
GO

-- Punto 9
/*Los 3 productos con mayor cantidad de reposición por mes.*/
CREATE VIEW BI_CODIGO_ENIGMA.BI_VISTA_punto_9
AS
   	SELECT A.DIM_TIEMPO_ANIO AS AÑO, A.DIM_TIEMPO_MES AS MES, A.PRODUCTO_VARIANTE_CODIGO, A.CANTIDAD
	FROM (SELECT ROW_NUMBER() OVER (PARTITION BY T.DIM_TIEMPO_MES ORDER BY SUM(CP.COMPRA_PRODUCTO_CANTIDAD) DESC ) R, T.DIM_TIEMPO_ANIO, T.DIM_TIEMPO_MES, CP.PRODUCTO_VARIANTE_CODIGO, SUM(CP.COMPRA_PRODUCTO_CANTIDAD) as CANTIDAD
			FROM BI_CODIGO_ENIGMA.BI_HECHO_COMPRA_PRODUCTO CP
			JOIN BI_CODIGO_ENIGMA.BI_DIM_TIEMPO T ON T.DIM_TIEMPO_CODIGO = CP.DIM_TIEMPO_CODIGO
			GROUP BY T.DIM_TIEMPO_ANIO, T.DIM_TIEMPO_MES, CP.PRODUCTO_VARIANTE_CODIGO) A
	WHERE R>0 AND R <= 3
GO



select * from BI_CODIGO_ENIGMA.bi_vista_punto_1
select * from BI_CODIGO_ENIGMA.bi_vista_punto_2
select * from BI_CODIGO_ENIGMA.bi_vista_punto_3
select * from BI_CODIGO_ENIGMA.bi_vista_punto_4
select * from BI_CODIGO_ENIGMA.bi_vista_punto_5
select * from BI_CODIGO_ENIGMA.bi_vista_punto_6
select * from BI_CODIGO_ENIGMA.bi_vista_punto_7
select * from BI_CODIGO_ENIGMA.BI_VISTA_punto_8
select * from BI_CODIGO_ENIGMA.BI_VISTA_punto_9